// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: poll/v1/poll.proto

package pollv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PollService_CreatePoll_FullMethodName     = "/poll.v1.PollService/CreatePoll"
	PollService_GetPollByToken_FullMethodName = "/poll.v1.PollService/GetPollByToken"
	PollService_SubmitResponse_FullMethodName = "/poll.v1.PollService/SubmitResponse"
	PollService_GetResponses_FullMethodName   = "/poll.v1.PollService/GetResponses"
)

// PollServiceClient is the client API for PollService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PollService owns the anonymous, link-scoped two-sided poll flow. CreatePoll and
// GetResponses are owner-scoped (JWT subject); GetPollByToken and SubmitResponse are
// anonymous and reached by an opaque, expiring, single-poll link token.
type PollServiceClient interface {
	// CreatePoll mints a poll and an opaque expiring link token (returned once).
	CreatePoll(ctx context.Context, in *CreatePollRequest, opts ...grpc.CallOption) (*CreatePollResponse, error)
	// GetPollByToken resolves the link token to its poll. Anonymous. Expired,
	// revoked, unknown or already-consumed tokens all return NotFound uniformly.
	GetPollByToken(ctx context.Context, in *GetPollByTokenRequest, opts ...grpc.CallOption) (*GetPollByTokenResponse, error)
	// SubmitResponse records the Subject's answers. Anonymous, rate-limited, one
	// response per poll; emits PollCompleted on success.
	SubmitResponse(ctx context.Context, in *SubmitResponseRequest, opts ...grpc.CallOption) (*SubmitResponseResponse, error)
	// GetResponses returns a poll's responses. Owner-only (JWT subject must equal
	// the poll's owner_user_id).
	GetResponses(ctx context.Context, in *GetResponsesRequest, opts ...grpc.CallOption) (*GetResponsesResponse, error)
}

type pollServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPollServiceClient(cc grpc.ClientConnInterface) PollServiceClient {
	return &pollServiceClient{cc}
}

func (c *pollServiceClient) CreatePoll(ctx context.Context, in *CreatePollRequest, opts ...grpc.CallOption) (*CreatePollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePollResponse)
	err := c.cc.Invoke(ctx, PollService_CreatePoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) GetPollByToken(ctx context.Context, in *GetPollByTokenRequest, opts ...grpc.CallOption) (*GetPollByTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPollByTokenResponse)
	err := c.cc.Invoke(ctx, PollService_GetPollByToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) SubmitResponse(ctx context.Context, in *SubmitResponseRequest, opts ...grpc.CallOption) (*SubmitResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponseResponse)
	err := c.cc.Invoke(ctx, PollService_SubmitResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollServiceClient) GetResponses(ctx context.Context, in *GetResponsesRequest, opts ...grpc.CallOption) (*GetResponsesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponsesResponse)
	err := c.cc.Invoke(ctx, PollService_GetResponses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PollServiceServer is the server API for PollService service.
// All implementations must embed UnimplementedPollServiceServer
// for forward compatibility.
//
// PollService owns the anonymous, link-scoped two-sided poll flow. CreatePoll and
// GetResponses are owner-scoped (JWT subject); GetPollByToken and SubmitResponse are
// anonymous and reached by an opaque, expiring, single-poll link token.
type PollServiceServer interface {
	// CreatePoll mints a poll and an opaque expiring link token (returned once).
	CreatePoll(context.Context, *CreatePollRequest) (*CreatePollResponse, error)
	// GetPollByToken resolves the link token to its poll. Anonymous. Expired,
	// revoked, unknown or already-consumed tokens all return NotFound uniformly.
	GetPollByToken(context.Context, *GetPollByTokenRequest) (*GetPollByTokenResponse, error)
	// SubmitResponse records the Subject's answers. Anonymous, rate-limited, one
	// response per poll; emits PollCompleted on success.
	SubmitResponse(context.Context, *SubmitResponseRequest) (*SubmitResponseResponse, error)
	// GetResponses returns a poll's responses. Owner-only (JWT subject must equal
	// the poll's owner_user_id).
	GetResponses(context.Context, *GetResponsesRequest) (*GetResponsesResponse, error)
	mustEmbedUnimplementedPollServiceServer()
}

// UnimplementedPollServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPollServiceServer struct{}

func (UnimplementedPollServiceServer) CreatePoll(context.Context, *CreatePollRequest) (*CreatePollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePoll not implemented")
}
func (UnimplementedPollServiceServer) GetPollByToken(context.Context, *GetPollByTokenRequest) (*GetPollByTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPollByToken not implemented")
}
func (UnimplementedPollServiceServer) SubmitResponse(context.Context, *SubmitResponseRequest) (*SubmitResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResponse not implemented")
}
func (UnimplementedPollServiceServer) GetResponses(context.Context, *GetResponsesRequest) (*GetResponsesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResponses not implemented")
}
func (UnimplementedPollServiceServer) mustEmbedUnimplementedPollServiceServer() {}
func (UnimplementedPollServiceServer) testEmbeddedByValue()                     {}

// UnsafePollServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PollServiceServer will
// result in compilation errors.
type UnsafePollServiceServer interface {
	mustEmbedUnimplementedPollServiceServer()
}

func RegisterPollServiceServer(s grpc.ServiceRegistrar, srv PollServiceServer) {
	// If the following call panics, it indicates UnimplementedPollServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PollService_ServiceDesc, srv)
}

func _PollService_CreatePoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).CreatePoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_CreatePoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).CreatePoll(ctx, req.(*CreatePollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_GetPollByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPollByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).GetPollByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_GetPollByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).GetPollByToken(ctx, req.(*GetPollByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_SubmitResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).SubmitResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_SubmitResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).SubmitResponse(ctx, req.(*SubmitResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PollService_GetResponses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResponsesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServiceServer).GetResponses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PollService_GetResponses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServiceServer).GetResponses(ctx, req.(*GetResponsesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PollService_ServiceDesc is the grpc.ServiceDesc for PollService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PollService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poll.v1.PollService",
	HandlerType: (*PollServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePoll",
			Handler:    _PollService_CreatePoll_Handler,
		},
		{
			MethodName: "GetPollByToken",
			Handler:    _PollService_GetPollByToken_Handler,
		},
		{
			MethodName: "SubmitResponse",
			Handler:    _PollService_SubmitResponse_Handler,
		},
		{
			MethodName: "GetResponses",
			Handler:    _PollService_GetResponses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poll/v1/poll.proto",
}
