// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: poll/v1/poll.proto

package pollv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestionType int32

const (
	QuestionType_QUESTION_TYPE_UNSPECIFIED   QuestionType = 0
	QuestionType_QUESTION_TYPE_TEXT          QuestionType = 1 // free-text answer
	QuestionType_QUESTION_TYPE_SINGLE_CHOICE QuestionType = 2 // exactly one option id
	QuestionType_QUESTION_TYPE_MULTI_CHOICE  QuestionType = 3 // one or more option ids
)

// Enum value maps for QuestionType.
var (
	QuestionType_name = map[int32]string{
		0: "QUESTION_TYPE_UNSPECIFIED",
		1: "QUESTION_TYPE_TEXT",
		2: "QUESTION_TYPE_SINGLE_CHOICE",
		3: "QUESTION_TYPE_MULTI_CHOICE",
	}
	QuestionType_value = map[string]int32{
		"QUESTION_TYPE_UNSPECIFIED":   0,
		"QUESTION_TYPE_TEXT":          1,
		"QUESTION_TYPE_SINGLE_CHOICE": 2,
		"QUESTION_TYPE_MULTI_CHOICE":  3,
	}
)

func (x QuestionType) Enum() *QuestionType {
	p := new(QuestionType)
	*p = x
	return p
}

func (x QuestionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestionType) Descriptor() protoreflect.EnumDescriptor {
	return file_poll_v1_poll_proto_enumTypes[0].Descriptor()
}

func (QuestionType) Type() protoreflect.EnumType {
	return &file_poll_v1_poll_proto_enumTypes[0]
}

func (x QuestionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestionType.Descriptor instead.
func (QuestionType) EnumDescriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{0}
}

type Option struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_poll_v1_poll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{0}
}

func (x *Option) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Option) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Type          QuestionType           `protobuf:"varint,3,opt,name=type,proto3,enum=poll.v1.QuestionType" json:"type,omitempty"`
	Options       []*Option              `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"` // for choice types
	Required      bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_poll_v1_poll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{1}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Question) GetType() QuestionType {
	if x != nil {
		return x.Type
	}
	return QuestionType_QUESTION_TYPE_UNSPECIFIED
}

func (x *Question) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Question) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                            // for TEXT questions
	ChoiceIds     []string               `protobuf:"bytes,3,rep,name=choice_ids,json=choiceIds,proto3" json:"choice_ids,omitempty"` // for CHOICE questions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_poll_v1_poll_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{2}
}

func (x *Answer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Answer) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Answer) GetChoiceIds() []string {
	if x != nil {
		return x.ChoiceIds
	}
	return nil
}

// ---- CreatePoll (owner) ----
type CreatePollRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Title             string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Questions         []*Question            `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	SurpriseRequestId string                 `protobuf:"bytes,3,opt,name=surprise_request_id,json=surpriseRequestId,proto3" json:"surprise_request_id,omitempty"` // optional
	TtlSeconds        int64                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`                       // optional; server default if <= 0
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePollRequest) Reset() {
	*x = CreatePollRequest{}
	mi := &file_poll_v1_poll_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePollRequest) ProtoMessage() {}

func (x *CreatePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePollRequest.ProtoReflect.Descriptor instead.
func (*CreatePollRequest) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePollRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePollRequest) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *CreatePollRequest) GetSurpriseRequestId() string {
	if x != nil {
		return x.SurpriseRequestId
	}
	return ""
}

func (x *CreatePollRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreatePollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	LinkToken     string                 `protobuf:"bytes,2,opt,name=link_token,json=linkToken,proto3" json:"link_token,omitempty"` // raw opaque token, returned ONCE
	LinkUrl       string                 `protobuf:"bytes,3,opt,name=link_url,json=linkUrl,proto3" json:"link_url,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePollResponse) Reset() {
	*x = CreatePollResponse{}
	mi := &file_poll_v1_poll_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePollResponse) ProtoMessage() {}

func (x *CreatePollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePollResponse.ProtoReflect.Descriptor instead.
func (*CreatePollResponse) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePollResponse) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *CreatePollResponse) GetLinkToken() string {
	if x != nil {
		return x.LinkToken
	}
	return ""
}

func (x *CreatePollResponse) GetLinkUrl() string {
	if x != nil {
		return x.LinkUrl
	}
	return ""
}

func (x *CreatePollResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// ---- GetPollByToken (anonymous) ----
type GetPollByTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPollByTokenRequest) Reset() {
	*x = GetPollByTokenRequest{}
	mi := &file_poll_v1_poll_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollByTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollByTokenRequest) ProtoMessage() {}

func (x *GetPollByTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollByTokenRequest.ProtoReflect.Descriptor instead.
func (*GetPollByTokenRequest) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{5}
}

func (x *GetPollByTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetPollByTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Questions     []*Question            `protobuf:"bytes,3,rep,name=questions,proto3" json:"questions,omitempty"` // Deliberately no owner_user_id / surprise_request_id: no owner data leaked.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPollByTokenResponse) Reset() {
	*x = GetPollByTokenResponse{}
	mi := &file_poll_v1_poll_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollByTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollByTokenResponse) ProtoMessage() {}

func (x *GetPollByTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollByTokenResponse.ProtoReflect.Descriptor instead.
func (*GetPollByTokenResponse) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{6}
}

func (x *GetPollByTokenResponse) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *GetPollByTokenResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetPollByTokenResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

// ---- SubmitResponse (anonymous) ----
type SubmitResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Answers       []*Answer              `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponseRequest) Reset() {
	*x = SubmitResponseRequest{}
	mi := &file_poll_v1_poll_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponseRequest) ProtoMessage() {}

func (x *SubmitResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponseRequest.ProtoReflect.Descriptor instead.
func (*SubmitResponseRequest) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitResponseRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SubmitResponseRequest) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type SubmitResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponseResponse) Reset() {
	*x = SubmitResponseResponse{}
	mi := &file_poll_v1_poll_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponseResponse) ProtoMessage() {}

func (x *SubmitResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponseResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponseResponse) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitResponseResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// ---- GetResponses (owner) ----
type GetResponsesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponsesRequest) Reset() {
	*x = GetResponsesRequest{}
	mi := &file_poll_v1_poll_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponsesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponsesRequest) ProtoMessage() {}

func (x *GetResponsesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponsesRequest.ProtoReflect.Descriptor instead.
func (*GetResponsesRequest) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{9}
}

func (x *GetResponsesRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Answers       []*Answer              `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	SubmittedAt   string                 `protobuf:"bytes,3,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_poll_v1_poll_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{10}
}

func (x *Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *Response) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

type GetResponsesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*Response            `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponsesResponse) Reset() {
	*x = GetResponsesResponse{}
	mi := &file_poll_v1_poll_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponsesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponsesResponse) ProtoMessage() {}

func (x *GetResponsesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponsesResponse.ProtoReflect.Descriptor instead.
func (*GetResponsesResponse) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{11}
}

func (x *GetResponsesResponse) GetResponses() []*Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_poll_v1_poll_proto protoreflect.FileDescriptor

const file_poll_v1_poll_proto_rawDesc = "" +
	"\n" +
	"\x12poll/v1/poll.proto\x12\apoll.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\".\n" +
	"\x06Option\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\xc0\x01\n" +
	"\bQuestion\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12\x1f\n" +
	"\x06prompt\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06prompt\x123\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.poll.v1.QuestionTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04type\x12)\n" +
	"\aoptions\x18\x04 \x03(\v2\x0f.poll.v1.OptionR\aoptions\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\"e\n" +
	"\x06Answer\x12(\n" +
	"\vquestion_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"choice_ids\x18\x03 \x03(\tR\tchoiceIds\"\xbe\x01\n" +
	"\x11CreatePollRequest\x12\x1d\n" +
	"\x05title\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05title\x129\n" +
	"\tquestions\x18\x02 \x03(\v2\x11.poll.v1.QuestionB\b\xfaB\x05\x92\x01\x02\b\x01R\tquestions\x12.\n" +
	"\x13surprise_request_id\x18\x03 \x01(\tR\x11surpriseRequestId\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x03R\n" +
	"ttlSeconds\"\x86\x01\n" +
	"\x12CreatePollResponse\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12\x1d\n" +
	"\n" +
	"link_token\x18\x02 \x01(\tR\tlinkToken\x12\x19\n" +
	"\blink_url\x18\x03 \x01(\tR\alinkUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\"6\n" +
	"\x15GetPollByTokenRequest\x12\x1d\n" +
	"\x05token\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05token\"x\n" +
	"\x16GetPollByTokenResponse\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12/\n" +
	"\tquestions\x18\x03 \x03(\v2\x11.poll.v1.QuestionR\tquestions\"a\n" +
	"\x15SubmitResponseRequest\x12\x1d\n" +
	"\x05token\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05token\x12)\n" +
	"\aanswers\x18\x02 \x03(\v2\x0f.poll.v1.AnswerR\aanswers\"(\n" +
	"\x16SubmitResponseResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"7\n" +
	"\x13GetResponsesRequest\x12 \n" +
	"\apoll_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06pollId\"h\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\aanswers\x18\x02 \x03(\v2\x0f.poll.v1.AnswerR\aanswers\x12!\n" +
	"\fsubmitted_at\x18\x03 \x01(\tR\vsubmittedAt\"G\n" +
	"\x14GetResponsesResponse\x12/\n" +
	"\tresponses\x18\x01 \x03(\v2\x11.poll.v1.ResponseR\tresponses*\x86\x01\n" +
	"\fQuestionType\x12\x1d\n" +
	"\x19QUESTION_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12QUESTION_TYPE_TEXT\x10\x01\x12\x1f\n" +
	"\x1bQUESTION_TYPE_SINGLE_CHOICE\x10\x02\x12\x1e\n" +
	"\x1aQUESTION_TYPE_MULTI_CHOICE\x10\x032\xd3\x03\n" +
	"\vPollService\x12[\n" +
	"\n" +
	"CreatePoll\x12\x1a.poll.v1.CreatePollRequest\x1a\x1b.poll.v1.CreatePollResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/polls\x12r\n" +
	"\x0eGetPollByToken\x12\x1e.poll.v1.GetPollByTokenRequest\x1a\x1f.poll.v1.GetPollByTokenResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/polls/token/{token}\x12\x7f\n" +
	"\x0eSubmitResponse\x12\x1e.poll.v1.SubmitResponseRequest\x1a\x1f.poll.v1.SubmitResponseResponse\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/polls/token/{token}/responses\x12r\n" +
	"\fGetResponses\x12\x1c.poll.v1.GetResponsesRequest\x1a\x1d.poll.v1.GetResponsesResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/polls/{poll_id}/responsesBSZQgithub.com/ilikyantigran/PerfectGift/services/backend/poll/pkg/api/poll/v1;pollv1b\x06proto3"

var (
	file_poll_v1_poll_proto_rawDescOnce sync.Once
	file_poll_v1_poll_proto_rawDescData []byte
)

func file_poll_v1_poll_proto_rawDescGZIP() []byte {
	file_poll_v1_poll_proto_rawDescOnce.Do(func() {
		file_poll_v1_poll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poll_v1_poll_proto_rawDesc), len(file_poll_v1_poll_proto_rawDesc)))
	})
	return file_poll_v1_poll_proto_rawDescData
}

var file_poll_v1_poll_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_poll_v1_poll_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_poll_v1_poll_proto_goTypes = []any{
	(QuestionType)(0),              // 0: poll.v1.QuestionType
	(*Option)(nil),                 // 1: poll.v1.Option
	(*Question)(nil),               // 2: poll.v1.Question
	(*Answer)(nil),                 // 3: poll.v1.Answer
	(*CreatePollRequest)(nil),      // 4: poll.v1.CreatePollRequest
	(*CreatePollResponse)(nil),     // 5: poll.v1.CreatePollResponse
	(*GetPollByTokenRequest)(nil),  // 6: poll.v1.GetPollByTokenRequest
	(*GetPollByTokenResponse)(nil), // 7: poll.v1.GetPollByTokenResponse
	(*SubmitResponseRequest)(nil),  // 8: poll.v1.SubmitResponseRequest
	(*SubmitResponseResponse)(nil), // 9: poll.v1.SubmitResponseResponse
	(*GetResponsesRequest)(nil),    // 10: poll.v1.GetResponsesRequest
	(*Response)(nil),               // 11: poll.v1.Response
	(*GetResponsesResponse)(nil),   // 12: poll.v1.GetResponsesResponse
}
var file_poll_v1_poll_proto_depIdxs = []int32{
	0,  // 0: poll.v1.Question.type:type_name -> poll.v1.QuestionType
	1,  // 1: poll.v1.Question.options:type_name -> poll.v1.Option
	2,  // 2: poll.v1.CreatePollRequest.questions:type_name -> poll.v1.Question
	2,  // 3: poll.v1.GetPollByTokenResponse.questions:type_name -> poll.v1.Question
	3,  // 4: poll.v1.SubmitResponseRequest.answers:type_name -> poll.v1.Answer
	3,  // 5: poll.v1.Response.answers:type_name -> poll.v1.Answer
	11, // 6: poll.v1.GetResponsesResponse.responses:type_name -> poll.v1.Response
	4,  // 7: poll.v1.PollService.CreatePoll:input_type -> poll.v1.CreatePollRequest
	6,  // 8: poll.v1.PollService.GetPollByToken:input_type -> poll.v1.GetPollByTokenRequest
	8,  // 9: poll.v1.PollService.SubmitResponse:input_type -> poll.v1.SubmitResponseRequest
	10, // 10: poll.v1.PollService.GetResponses:input_type -> poll.v1.GetResponsesRequest
	5,  // 11: poll.v1.PollService.CreatePoll:output_type -> poll.v1.CreatePollResponse
	7,  // 12: poll.v1.PollService.GetPollByToken:output_type -> poll.v1.GetPollByTokenResponse
	9,  // 13: poll.v1.PollService.SubmitResponse:output_type -> poll.v1.SubmitResponseResponse
	12, // 14: poll.v1.PollService.GetResponses:output_type -> poll.v1.GetResponsesResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_poll_v1_poll_proto_init() }
func file_poll_v1_poll_proto_init() {
	if File_poll_v1_poll_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poll_v1_poll_proto_rawDesc), len(file_poll_v1_poll_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poll_v1_poll_proto_goTypes,
		DependencyIndexes: file_poll_v1_poll_proto_depIdxs,
		EnumInfos:         file_poll_v1_poll_proto_enumTypes,
		MessageInfos:      file_poll_v1_poll_proto_msgTypes,
	}.Build()
	File_poll_v1_poll_proto = out.File
	file_poll_v1_poll_proto_goTypes = nil
	file_poll_v1_poll_proto_depIdxs = nil
}
