// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: poll/v1/poll.proto

package pollv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Poll_CreatePoll_FullMethodName     = "/poll.v1.Poll/CreatePoll"
	Poll_GetPollByToken_FullMethodName = "/poll.v1.Poll/GetPollByToken"
	Poll_SubmitResponse_FullMethodName = "/poll.v1.Poll/SubmitResponse"
	Poll_GetResponses_FullMethodName   = "/poll.v1.Poll/GetResponses"
)

// PollClient is the client API for Poll service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PollClient interface {
	CreatePoll(ctx context.Context, in *CreatePollRequest, opts ...grpc.CallOption) (*CreatePollResponse, error)
	GetPollByToken(ctx context.Context, in *GetPollByTokenRequest, opts ...grpc.CallOption) (*GetPollByTokenResponse, error)
	SubmitResponse(ctx context.Context, in *SubmitResponseRequest, opts ...grpc.CallOption) (*SubmitResponseResponse, error)
	GetResponses(ctx context.Context, in *GetResponsesRequest, opts ...grpc.CallOption) (*GetResponsesResponse, error)
}

type pollClient struct {
	cc grpc.ClientConnInterface
}

func NewPollClient(cc grpc.ClientConnInterface) PollClient {
	return &pollClient{cc}
}

func (c *pollClient) CreatePoll(ctx context.Context, in *CreatePollRequest, opts ...grpc.CallOption) (*CreatePollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePollResponse)
	err := c.cc.Invoke(ctx, Poll_CreatePoll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollClient) GetPollByToken(ctx context.Context, in *GetPollByTokenRequest, opts ...grpc.CallOption) (*GetPollByTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPollByTokenResponse)
	err := c.cc.Invoke(ctx, Poll_GetPollByToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollClient) SubmitResponse(ctx context.Context, in *SubmitResponseRequest, opts ...grpc.CallOption) (*SubmitResponseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitResponseResponse)
	err := c.cc.Invoke(ctx, Poll_SubmitResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pollClient) GetResponses(ctx context.Context, in *GetResponsesRequest, opts ...grpc.CallOption) (*GetResponsesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponsesResponse)
	err := c.cc.Invoke(ctx, Poll_GetResponses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PollServer is the server API for Poll service.
// All implementations must embed UnimplementedPollServer
// for forward compatibility.
type PollServer interface {
	CreatePoll(context.Context, *CreatePollRequest) (*CreatePollResponse, error)
	GetPollByToken(context.Context, *GetPollByTokenRequest) (*GetPollByTokenResponse, error)
	SubmitResponse(context.Context, *SubmitResponseRequest) (*SubmitResponseResponse, error)
	GetResponses(context.Context, *GetResponsesRequest) (*GetResponsesResponse, error)
	mustEmbedUnimplementedPollServer()
}

// UnimplementedPollServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPollServer struct{}

func (UnimplementedPollServer) CreatePoll(context.Context, *CreatePollRequest) (*CreatePollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePoll not implemented")
}
func (UnimplementedPollServer) GetPollByToken(context.Context, *GetPollByTokenRequest) (*GetPollByTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPollByToken not implemented")
}
func (UnimplementedPollServer) SubmitResponse(context.Context, *SubmitResponseRequest) (*SubmitResponseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResponse not implemented")
}
func (UnimplementedPollServer) GetResponses(context.Context, *GetResponsesRequest) (*GetResponsesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResponses not implemented")
}
func (UnimplementedPollServer) mustEmbedUnimplementedPollServer() {}
func (UnimplementedPollServer) testEmbeddedByValue()              {}

// UnsafePollServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PollServer will
// result in compilation errors.
type UnsafePollServer interface {
	mustEmbedUnimplementedPollServer()
}

func RegisterPollServer(s grpc.ServiceRegistrar, srv PollServer) {
	// If the following call panics, it indicates UnimplementedPollServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Poll_ServiceDesc, srv)
}

func _Poll_CreatePoll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServer).CreatePoll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Poll_CreatePoll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServer).CreatePoll(ctx, req.(*CreatePollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poll_GetPollByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPollByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServer).GetPollByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Poll_GetPollByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServer).GetPollByToken(ctx, req.(*GetPollByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poll_SubmitResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServer).SubmitResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Poll_SubmitResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServer).SubmitResponse(ctx, req.(*SubmitResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poll_GetResponses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResponsesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PollServer).GetResponses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Poll_GetResponses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PollServer).GetResponses(ctx, req.(*GetResponsesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Poll_ServiceDesc is the grpc.ServiceDesc for Poll service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Poll_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "poll.v1.Poll",
	HandlerType: (*PollServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePoll",
			Handler:    _Poll_CreatePoll_Handler,
		},
		{
			MethodName: "GetPollByToken",
			Handler:    _Poll_GetPollByToken_Handler,
		},
		{
			MethodName: "SubmitResponse",
			Handler:    _Poll_SubmitResponse_Handler,
		},
		{
			MethodName: "GetResponses",
			Handler:    _Poll_GetResponses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "poll/v1/poll.proto",
}
