// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: poll/v1/poll.proto

package pollv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // e.g. single_choice | multi_choice | free_text
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_poll_v1_poll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Question) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Question) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Values        []string               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_poll_v1_poll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{1}
}

func (x *Answer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Answer) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Answer) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// owner_user_id is injected by the gateway from the JWT subject, not the body.
type CreatePollRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OwnerUserId       string                 `protobuf:"bytes,1,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Questions         []*Question            `protobuf:"bytes,3,rep,name=questions,proto3" json:"questions,omitempty"`
	SurpriseRequestId string                 `protobuf:"bytes,4,opt,name=surprise_request_id,json=surpriseRequestId,proto3" json:"surprise_request_id,omitempty"`
	TtlSeconds        int64                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePollRequest) Reset() {
	*x = CreatePollRequest{}
	mi := &file_poll_v1_poll_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePollRequest) ProtoMessage() {}

func (x *CreatePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePollRequest.ProtoReflect.Descriptor instead.
func (*CreatePollRequest) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePollRequest) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *CreatePollRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePollRequest) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *CreatePollRequest) GetSurpriseRequestId() string {
	if x != nil {
		return x.SurpriseRequestId
	}
	return ""
}

func (x *CreatePollRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreatePollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	LinkToken     string                 `protobuf:"bytes,2,opt,name=link_token,json=linkToken,proto3" json:"link_token,omitempty"` // raw token, returned once
	LinkUrl       string                 `protobuf:"bytes,3,opt,name=link_url,json=linkUrl,proto3" json:"link_url,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePollResponse) Reset() {
	*x = CreatePollResponse{}
	mi := &file_poll_v1_poll_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePollResponse) ProtoMessage() {}

func (x *CreatePollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePollResponse.ProtoReflect.Descriptor instead.
func (*CreatePollResponse) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePollResponse) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *CreatePollResponse) GetLinkToken() string {
	if x != nil {
		return x.LinkToken
	}
	return ""
}

func (x *CreatePollResponse) GetLinkUrl() string {
	if x != nil {
		return x.LinkUrl
	}
	return ""
}

func (x *CreatePollResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type GetPollByTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPollByTokenRequest) Reset() {
	*x = GetPollByTokenRequest{}
	mi := &file_poll_v1_poll_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollByTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollByTokenRequest) ProtoMessage() {}

func (x *GetPollByTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollByTokenRequest.ProtoReflect.Descriptor instead.
func (*GetPollByTokenRequest) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{4}
}

func (x *GetPollByTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetPollByTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Questions     []*Question            `protobuf:"bytes,3,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPollByTokenResponse) Reset() {
	*x = GetPollByTokenResponse{}
	mi := &file_poll_v1_poll_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPollByTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPollByTokenResponse) ProtoMessage() {}

func (x *GetPollByTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPollByTokenResponse.ProtoReflect.Descriptor instead.
func (*GetPollByTokenResponse) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{5}
}

func (x *GetPollByTokenResponse) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *GetPollByTokenResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetPollByTokenResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type SubmitResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Answers       []*Answer              `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponseRequest) Reset() {
	*x = SubmitResponseRequest{}
	mi := &file_poll_v1_poll_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponseRequest) ProtoMessage() {}

func (x *SubmitResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponseRequest.ProtoReflect.Descriptor instead.
func (*SubmitResponseRequest) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitResponseRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SubmitResponseRequest) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type SubmitResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponseResponse) Reset() {
	*x = SubmitResponseResponse{}
	mi := &file_poll_v1_poll_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponseResponse) ProtoMessage() {}

func (x *SubmitResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponseResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponseResponse) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitResponseResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// owner_user_id from the JWT subject; the service enforces owner-scoped authz.
type GetResponsesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        string                 `protobuf:"bytes,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,2,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponsesRequest) Reset() {
	*x = GetResponsesRequest{}
	mi := &file_poll_v1_poll_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponsesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponsesRequest) ProtoMessage() {}

func (x *GetResponsesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponsesRequest.ProtoReflect.Descriptor instead.
func (*GetResponsesRequest) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{8}
}

func (x *GetResponsesRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *GetResponsesRequest) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Answers       []*Answer              `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	SubmittedAt   string                 `protobuf:"bytes,3,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_poll_v1_poll_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{9}
}

func (x *PollResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PollResponse) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *PollResponse) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

type GetResponsesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*PollResponse        `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponsesResponse) Reset() {
	*x = GetResponsesResponse{}
	mi := &file_poll_v1_poll_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponsesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponsesResponse) ProtoMessage() {}

func (x *GetResponsesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_v1_poll_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponsesResponse.ProtoReflect.Descriptor instead.
func (*GetResponsesResponse) Descriptor() ([]byte, []int) {
	return file_poll_v1_poll_proto_rawDescGZIP(), []int{10}
}

func (x *GetResponsesResponse) GetResponses() []*PollResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_poll_v1_poll_proto protoreflect.FileDescriptor

const file_poll_v1_poll_proto_rawDesc = "" +
	"\n" +
	"\x12poll/v1/poll.proto\x12\apoll.v1\"\\\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\"W\n" +
	"\x06Answer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\"\xcf\x01\n" +
	"\x11CreatePollRequest\x12\"\n" +
	"\rowner_user_id\x18\x01 \x01(\tR\vownerUserId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12/\n" +
	"\tquestions\x18\x03 \x03(\v2\x11.poll.v1.QuestionR\tquestions\x12.\n" +
	"\x13surprise_request_id\x18\x04 \x01(\tR\x11surpriseRequestId\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x03R\n" +
	"ttlSeconds\"\x86\x01\n" +
	"\x12CreatePollResponse\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12\x1d\n" +
	"\n" +
	"link_token\x18\x02 \x01(\tR\tlinkToken\x12\x19\n" +
	"\blink_url\x18\x03 \x01(\tR\alinkUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\"-\n" +
	"\x15GetPollByTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"x\n" +
	"\x16GetPollByTokenResponse\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12/\n" +
	"\tquestions\x18\x03 \x03(\v2\x11.poll.v1.QuestionR\tquestions\"X\n" +
	"\x15SubmitResponseRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12)\n" +
	"\aanswers\x18\x02 \x03(\v2\x0f.poll.v1.AnswerR\aanswers\"(\n" +
	"\x16SubmitResponseResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"R\n" +
	"\x13GetResponsesRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\tR\x06pollId\x12\"\n" +
	"\rowner_user_id\x18\x02 \x01(\tR\vownerUserId\"l\n" +
	"\fPollResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\aanswers\x18\x02 \x03(\v2\x0f.poll.v1.AnswerR\aanswers\x12!\n" +
	"\fsubmitted_at\x18\x03 \x01(\tR\vsubmittedAt\"K\n" +
	"\x14GetResponsesResponse\x123\n" +
	"\tresponses\x18\x01 \x03(\v2\x15.poll.v1.PollResponseR\tresponses2\xc0\x02\n" +
	"\x04Poll\x12E\n" +
	"\n" +
	"CreatePoll\x12\x1a.poll.v1.CreatePollRequest\x1a\x1b.poll.v1.CreatePollResponse\x12Q\n" +
	"\x0eGetPollByToken\x12\x1e.poll.v1.GetPollByTokenRequest\x1a\x1f.poll.v1.GetPollByTokenResponse\x12Q\n" +
	"\x0eSubmitResponse\x12\x1e.poll.v1.SubmitResponseRequest\x1a\x1f.poll.v1.SubmitResponseResponse\x12K\n" +
	"\fGetResponses\x12\x1c.poll.v1.GetResponsesRequest\x1a\x1d.poll.v1.GetResponsesResponseBZZXgithub.com/ilikyantigran/PerfectGift/services/backend/api-gateway/pkg/api/poll/v1;pollv1b\x06proto3"

var (
	file_poll_v1_poll_proto_rawDescOnce sync.Once
	file_poll_v1_poll_proto_rawDescData []byte
)

func file_poll_v1_poll_proto_rawDescGZIP() []byte {
	file_poll_v1_poll_proto_rawDescOnce.Do(func() {
		file_poll_v1_poll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poll_v1_poll_proto_rawDesc), len(file_poll_v1_poll_proto_rawDesc)))
	})
	return file_poll_v1_poll_proto_rawDescData
}

var file_poll_v1_poll_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_poll_v1_poll_proto_goTypes = []any{
	(*Question)(nil),               // 0: poll.v1.Question
	(*Answer)(nil),                 // 1: poll.v1.Answer
	(*CreatePollRequest)(nil),      // 2: poll.v1.CreatePollRequest
	(*CreatePollResponse)(nil),     // 3: poll.v1.CreatePollResponse
	(*GetPollByTokenRequest)(nil),  // 4: poll.v1.GetPollByTokenRequest
	(*GetPollByTokenResponse)(nil), // 5: poll.v1.GetPollByTokenResponse
	(*SubmitResponseRequest)(nil),  // 6: poll.v1.SubmitResponseRequest
	(*SubmitResponseResponse)(nil), // 7: poll.v1.SubmitResponseResponse
	(*GetResponsesRequest)(nil),    // 8: poll.v1.GetResponsesRequest
	(*PollResponse)(nil),           // 9: poll.v1.PollResponse
	(*GetResponsesResponse)(nil),   // 10: poll.v1.GetResponsesResponse
}
var file_poll_v1_poll_proto_depIdxs = []int32{
	0,  // 0: poll.v1.CreatePollRequest.questions:type_name -> poll.v1.Question
	0,  // 1: poll.v1.GetPollByTokenResponse.questions:type_name -> poll.v1.Question
	1,  // 2: poll.v1.SubmitResponseRequest.answers:type_name -> poll.v1.Answer
	1,  // 3: poll.v1.PollResponse.answers:type_name -> poll.v1.Answer
	9,  // 4: poll.v1.GetResponsesResponse.responses:type_name -> poll.v1.PollResponse
	2,  // 5: poll.v1.Poll.CreatePoll:input_type -> poll.v1.CreatePollRequest
	4,  // 6: poll.v1.Poll.GetPollByToken:input_type -> poll.v1.GetPollByTokenRequest
	6,  // 7: poll.v1.Poll.SubmitResponse:input_type -> poll.v1.SubmitResponseRequest
	8,  // 8: poll.v1.Poll.GetResponses:input_type -> poll.v1.GetResponsesRequest
	3,  // 9: poll.v1.Poll.CreatePoll:output_type -> poll.v1.CreatePollResponse
	5,  // 10: poll.v1.Poll.GetPollByToken:output_type -> poll.v1.GetPollByTokenResponse
	7,  // 11: poll.v1.Poll.SubmitResponse:output_type -> poll.v1.SubmitResponseResponse
	10, // 12: poll.v1.Poll.GetResponses:output_type -> poll.v1.GetResponsesResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_poll_v1_poll_proto_init() }
func file_poll_v1_poll_proto_init() {
	if File_poll_v1_poll_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poll_v1_poll_proto_rawDesc), len(file_poll_v1_poll_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poll_v1_poll_proto_goTypes,
		DependencyIndexes: file_poll_v1_poll_proto_depIdxs,
		MessageInfos:      file_poll_v1_poll_proto_msgTypes,
	}.Build()
	File_poll_v1_poll_proto = out.File
	file_poll_v1_poll_proto_goTypes = nil
	file_poll_v1_poll_proto_depIdxs = nil
}
