// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: catalog/v1/catalog.proto

package catalogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_ListHolidays_FullMethodName      = "/catalog.v1.CatalogService/ListHolidays"
	CatalogService_GetCategories_FullMethodName     = "/catalog.v1.CatalogService/GetCategories"
	CatalogService_SearchInspiration_FullMethodName = "/catalog.v1.CatalogService/SearchInspiration"
	CatalogService_UpsertInspiration_FullMethodName = "/catalog.v1.CatalogService/UpsertInspiration"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CatalogService is PerfectGift's read-mostly reference + grounding service.
// ListHolidays / GetCategories are cached client reads (exposed via the gateway).
// SearchInspiration is internal-only (pgvector grounding for the Surprise worker).
// UpsertInspiration is the rare admin/editorial write path.
type CatalogServiceClient interface {
	// Client reference read. region/active/on_or_after bind as query params:
	// GET /v1/holidays?region=&active=&on_or_after=
	ListHolidays(ctx context.Context, in *ListHolidaysRequest, opts ...grpc.CallOption) (*ListHolidaysResponse, error)
	// Client reference read. kind binds as a query param:
	// GET /v1/categories?kind=
	GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	// INTERNAL ONLY (called by Surprise). pgvector similarity search over the
	// curated corpus. Never exposed on the public REST edge — no HTTP annotation.
	SearchInspiration(ctx context.Context, in *SearchInspirationRequest, opts ...grpc.CallOption) (*SearchInspirationResponse, error)
	// ADMIN/EDITORIAL. (Re)computes the embedding, upserts the row, invalidates the
	// reference cache. No HTTP annotation (not a client-facing call).
	UpsertInspiration(ctx context.Context, in *UpsertInspirationRequest, opts ...grpc.CallOption) (*UpsertInspirationResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) ListHolidays(ctx context.Context, in *ListHolidaysRequest, opts ...grpc.CallOption) (*ListHolidaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHolidaysResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListHolidays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) SearchInspiration(ctx context.Context, in *SearchInspirationRequest, opts ...grpc.CallOption) (*SearchInspirationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchInspirationResponse)
	err := c.cc.Invoke(ctx, CatalogService_SearchInspiration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpsertInspiration(ctx context.Context, in *UpsertInspirationRequest, opts ...grpc.CallOption) (*UpsertInspirationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertInspirationResponse)
	err := c.cc.Invoke(ctx, CatalogService_UpsertInspiration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
//
// CatalogService is PerfectGift's read-mostly reference + grounding service.
// ListHolidays / GetCategories are cached client reads (exposed via the gateway).
// SearchInspiration is internal-only (pgvector grounding for the Surprise worker).
// UpsertInspiration is the rare admin/editorial write path.
type CatalogServiceServer interface {
	// Client reference read. region/active/on_or_after bind as query params:
	// GET /v1/holidays?region=&active=&on_or_after=
	ListHolidays(context.Context, *ListHolidaysRequest) (*ListHolidaysResponse, error)
	// Client reference read. kind binds as a query param:
	// GET /v1/categories?kind=
	GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error)
	// INTERNAL ONLY (called by Surprise). pgvector similarity search over the
	// curated corpus. Never exposed on the public REST edge — no HTTP annotation.
	SearchInspiration(context.Context, *SearchInspirationRequest) (*SearchInspirationResponse, error)
	// ADMIN/EDITORIAL. (Re)computes the embedding, upserts the row, invalidates the
	// reference cache. No HTTP annotation (not a client-facing call).
	UpsertInspiration(context.Context, *UpsertInspirationRequest) (*UpsertInspirationResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) ListHolidays(context.Context, *ListHolidaysRequest) (*ListHolidaysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHolidays not implemented")
}
func (UnimplementedCatalogServiceServer) GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategories not implemented")
}
func (UnimplementedCatalogServiceServer) SearchInspiration(context.Context, *SearchInspirationRequest) (*SearchInspirationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchInspiration not implemented")
}
func (UnimplementedCatalogServiceServer) UpsertInspiration(context.Context, *UpsertInspirationRequest) (*UpsertInspirationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertInspiration not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_ListHolidays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHolidaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListHolidays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListHolidays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListHolidays(ctx, req.(*ListHolidaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetCategories(ctx, req.(*GetCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_SearchInspiration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchInspirationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).SearchInspiration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_SearchInspiration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).SearchInspiration(ctx, req.(*SearchInspirationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpsertInspiration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertInspirationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpsertInspiration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpsertInspiration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpsertInspiration(ctx, req.(*UpsertInspirationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.v1.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHolidays",
			Handler:    _CatalogService_ListHolidays_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _CatalogService_GetCategories_Handler,
		},
		{
			MethodName: "SearchInspiration",
			Handler:    _CatalogService_SearchInspiration_Handler,
		},
		{
			MethodName: "UpsertInspiration",
			Handler:    _CatalogService_UpsertInspiration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog/v1/catalog.proto",
}
