// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: catalog/v1/catalog.proto

package catalogv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DateRule int32

const (
	DateRule_DATE_RULE_UNSPECIFIED DateRule = 0
	DateRule_DATE_RULE_FIXED       DateRule = 1 // same calendar date every year (e.g. Feb 14)
	DateRule_DATE_RULE_RELATIVE    DateRule = 2 // computed each year (e.g. "second Sunday of May")
)

// Enum value maps for DateRule.
var (
	DateRule_name = map[int32]string{
		0: "DATE_RULE_UNSPECIFIED",
		1: "DATE_RULE_FIXED",
		2: "DATE_RULE_RELATIVE",
	}
	DateRule_value = map[string]int32{
		"DATE_RULE_UNSPECIFIED": 0,
		"DATE_RULE_FIXED":       1,
		"DATE_RULE_RELATIVE":    2,
	}
)

func (x DateRule) Enum() *DateRule {
	p := new(DateRule)
	*p = x
	return p
}

func (x DateRule) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DateRule) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_v1_catalog_proto_enumTypes[0].Descriptor()
}

func (DateRule) Type() protoreflect.EnumType {
	return &file_catalog_v1_catalog_proto_enumTypes[0]
}

func (x DateRule) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DateRule.Descriptor instead.
func (DateRule) EnumDescriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

type CategoryKind int32

const (
	CategoryKind_CATEGORY_KIND_UNSPECIFIED CategoryKind = 0
	CategoryKind_CATEGORY_KIND_GIFT        CategoryKind = 1
	CategoryKind_CATEGORY_KIND_DATE        CategoryKind = 2
)

// Enum value maps for CategoryKind.
var (
	CategoryKind_name = map[int32]string{
		0: "CATEGORY_KIND_UNSPECIFIED",
		1: "CATEGORY_KIND_GIFT",
		2: "CATEGORY_KIND_DATE",
	}
	CategoryKind_value = map[string]int32{
		"CATEGORY_KIND_UNSPECIFIED": 0,
		"CATEGORY_KIND_GIFT":        1,
		"CATEGORY_KIND_DATE":        2,
	}
)

func (x CategoryKind) Enum() *CategoryKind {
	p := new(CategoryKind)
	*p = x
	return p
}

func (x CategoryKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CategoryKind) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_v1_catalog_proto_enumTypes[1].Descriptor()
}

func (CategoryKind) Type() protoreflect.EnumType {
	return &file_catalog_v1_catalog_proto_enumTypes[1]
}

func (x CategoryKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CategoryKind.Descriptor instead.
func (CategoryKind) EnumDescriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

type Holiday struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DateRule      DateRule               `protobuf:"varint,3,opt,name=date_rule,json=dateRule,proto3,enum=catalog.v1.DateRule" json:"date_rule,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Holiday) Reset() {
	*x = Holiday{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holiday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holiday) ProtoMessage() {}

func (x *Holiday) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holiday.ProtoReflect.Descriptor instead.
func (*Holiday) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Holiday) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Holiday) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Holiday) GetDateRule() DateRule {
	if x != nil {
		return x.DateRule
	}
	return DateRule_DATE_RULE_UNSPECIFIED
}

func (x *Holiday) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Holiday) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Holiday) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          CategoryKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=catalog.v1.CategoryKind" json:"kind,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // empty when top-level
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetKind() CategoryKind {
	if x != nil {
		return x.Kind
	}
	return CategoryKind_CATEGORY_KIND_UNSPECIFIED
}

func (x *Category) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type BudgetBand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	MinCents      int32                  `protobuf:"varint,3,opt,name=min_cents,json=minCents,proto3" json:"min_cents,omitempty"`
	MaxCents      int32                  `protobuf:"varint,4,opt,name=max_cents,json=maxCents,proto3" json:"max_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetBand) Reset() {
	*x = BudgetBand{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetBand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetBand) ProtoMessage() {}

func (x *BudgetBand) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetBand.ProtoReflect.Descriptor instead.
func (*BudgetBand) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *BudgetBand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BudgetBand) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BudgetBand) GetMinCents() int32 {
	if x != nil {
		return x.MinCents
	}
	return 0
}

func (x *BudgetBand) GetMaxCents() int32 {
	if x != nil {
		return x.MaxCents
	}
	return 0
}

func (x *BudgetBand) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Inspiration is the editorial corpus row. The embedding is never sent over the
// wire (computed server-side); it is not part of this message.
type Inspiration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // empty on create; set to update in place
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`         // optional
	BudgetBandId  string                 `protobuf:"bytes,5,opt,name=budget_band_id,json=budgetBandId,proto3" json:"budget_band_id,omitempty"` // optional
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	CuratedBy     string                 `protobuf:"bytes,7,opt,name=curated_by,json=curatedBy,proto3" json:"curated_by,omitempty"`
	Active        bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inspiration) Reset() {
	*x = Inspiration{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inspiration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inspiration) ProtoMessage() {}

func (x *Inspiration) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inspiration.ProtoReflect.Descriptor instead.
func (*Inspiration) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Inspiration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Inspiration) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Inspiration) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Inspiration) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Inspiration) GetBudgetBandId() string {
	if x != nil {
		return x.BudgetBandId
	}
	return ""
}

func (x *Inspiration) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Inspiration) GetCuratedBy() string {
	if x != nil {
		return x.CuratedBy
	}
	return ""
}

func (x *Inspiration) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// Snippet is a grounding result: an inspiration row plus its similarity score.
type Snippet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	BudgetBandId  string                 `protobuf:"bytes,5,opt,name=budget_band_id,json=budgetBandId,proto3" json:"budget_band_id,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"` // cosine similarity in [0,1]; higher is closer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snippet) Reset() {
	*x = Snippet{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snippet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snippet) ProtoMessage() {}

func (x *Snippet) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snippet.ProtoReflect.Descriptor instead.
func (*Snippet) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *Snippet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Snippet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Snippet) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Snippet) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Snippet) GetBudgetBandId() string {
	if x != nil {
		return x.BudgetBandId
	}
	return ""
}

func (x *Snippet) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Snippet) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ListHolidaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`                          // optional filter
	Active        *bool                  `protobuf:"varint,2,opt,name=active,proto3,oneof" json:"active,omitempty"`                   // optional filter; unset = all
	OnOrAfter     string                 `protobuf:"bytes,3,opt,name=on_or_after,json=onOrAfter,proto3" json:"on_or_after,omitempty"` // optional ISO date (YYYY-MM-DD); reserved for date-aware filtering
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHolidaysRequest) Reset() {
	*x = ListHolidaysRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHolidaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHolidaysRequest) ProtoMessage() {}

func (x *ListHolidaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHolidaysRequest.ProtoReflect.Descriptor instead.
func (*ListHolidaysRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *ListHolidaysRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListHolidaysRequest) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ListHolidaysRequest) GetOnOrAfter() string {
	if x != nil {
		return x.OnOrAfter
	}
	return ""
}

type ListHolidaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holidays      []*Holiday             `protobuf:"bytes,1,rep,name=holidays,proto3" json:"holidays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHolidaysResponse) Reset() {
	*x = ListHolidaysResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHolidaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHolidaysResponse) ProtoMessage() {}

func (x *ListHolidaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHolidaysResponse.ProtoReflect.Descriptor instead.
func (*ListHolidaysResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ListHolidaysResponse) GetHolidays() []*Holiday {
	if x != nil {
		return x.Holidays
	}
	return nil
}

type GetCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          CategoryKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=catalog.v1.CategoryKind" json:"kind,omitempty"` // UNSPECIFIED = all kinds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesRequest) Reset() {
	*x = GetCategoriesRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesRequest) ProtoMessage() {}

func (x *GetCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetCategoriesRequest) GetKind() CategoryKind {
	if x != nil {
		return x.Kind
	}
	return CategoryKind_CATEGORY_KIND_UNSPECIFIED
}

type GetCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	BudgetBands   []*BudgetBand          `protobuf:"bytes,2,rep,name=budget_bands,json=budgetBands,proto3" json:"budget_bands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *GetCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetCategoriesResponse) GetBudgetBands() []*BudgetBand {
	if x != nil {
		return x.BudgetBands
	}
	return nil
}

type SearchFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`         // optional
	BudgetBandId  string                 `protobuf:"bytes,2,opt,name=budget_band_id,json=budgetBandId,proto3" json:"budget_band_id,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilters) Reset() {
	*x = SearchFilters{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilters) ProtoMessage() {}

func (x *SearchFilters) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilters.ProtoReflect.Descriptor instead.
func (*SearchFilters) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *SearchFilters) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *SearchFilters) GetBudgetBandId() string {
	if x != nil {
		return x.BudgetBandId
	}
	return ""
}

type SearchInspirationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provide exactly one of query_text or query_embedding.
	QueryText      string         `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`                         // server embeds it (must match Surprise's model)
	QueryEmbedding []float32      `protobuf:"fixed32,2,rep,packed,name=query_embedding,json=queryEmbedding,proto3" json:"query_embedding,omitempty"` // pre-computed by the caller; length must == configured dimension
	Filters        *SearchFilters `protobuf:"bytes,3,opt,name=filters,proto3" json:"filters,omitempty"`
	TopK           int32          `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"` // defaulted/capped server-side
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchInspirationRequest) Reset() {
	*x = SearchInspirationRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchInspirationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchInspirationRequest) ProtoMessage() {}

func (x *SearchInspirationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchInspirationRequest.ProtoReflect.Descriptor instead.
func (*SearchInspirationRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *SearchInspirationRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *SearchInspirationRequest) GetQueryEmbedding() []float32 {
	if x != nil {
		return x.QueryEmbedding
	}
	return nil
}

func (x *SearchInspirationRequest) GetFilters() *SearchFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchInspirationRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchInspirationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snippets      []*Snippet             `protobuf:"bytes,1,rep,name=snippets,proto3" json:"snippets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchInspirationResponse) Reset() {
	*x = SearchInspirationResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchInspirationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchInspirationResponse) ProtoMessage() {}

func (x *SearchInspirationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchInspirationResponse.ProtoReflect.Descriptor instead.
func (*SearchInspirationResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *SearchInspirationResponse) GetSnippets() []*Snippet {
	if x != nil {
		return x.Snippets
	}
	return nil
}

type UpsertInspirationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inspiration   *Inspiration           `protobuf:"bytes,1,opt,name=inspiration,proto3" json:"inspiration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertInspirationRequest) Reset() {
	*x = UpsertInspirationRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertInspirationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertInspirationRequest) ProtoMessage() {}

func (x *UpsertInspirationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertInspirationRequest.ProtoReflect.Descriptor instead.
func (*UpsertInspirationRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *UpsertInspirationRequest) GetInspiration() *Inspiration {
	if x != nil {
		return x.Inspiration
	}
	return nil
}

type UpsertInspirationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertInspirationResponse) Reset() {
	*x = UpsertInspirationResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertInspirationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertInspirationResponse) ProtoMessage() {}

func (x *UpsertInspirationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertInspirationResponse.ProtoReflect.Descriptor instead.
func (*UpsertInspirationResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *UpsertInspirationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/v1/catalog.proto\x12\n" +
	"catalog.v1\x1a\x1cgoogle/api/annotations.proto\"\xa4\x01\n" +
	"\aHoliday\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\tdate_rule\x18\x03 \x01(\x0e2\x14.catalog.v1.DateRuleR\bdateRule\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\"y\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x18.catalog.v1.CategoryKindR\x04kind\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\"\x88\x01\n" +
	"\n" +
	"BudgetBand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1b\n" +
	"\tmin_cents\x18\x03 \x01(\x05R\bminCents\x12\x1b\n" +
	"\tmax_cents\x18\x04 \x01(\x05R\bmaxCents\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"\xd9\x01\n" +
	"\vInspiration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12$\n" +
	"\x0ebudget_band_id\x18\x05 \x01(\tR\fbudgetBandId\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"curated_by\x18\a \x01(\tR\tcuratedBy\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\"\xb4\x01\n" +
	"\aSnippet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12$\n" +
	"\x0ebudget_band_id\x18\x05 \x01(\tR\fbudgetBandId\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\"u\n" +
	"\x13ListHolidaysRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x1b\n" +
	"\x06active\x18\x02 \x01(\bH\x00R\x06active\x88\x01\x01\x12\x1e\n" +
	"\von_or_after\x18\x03 \x01(\tR\tonOrAfterB\t\n" +
	"\a_active\"G\n" +
	"\x14ListHolidaysResponse\x12/\n" +
	"\bholidays\x18\x01 \x03(\v2\x13.catalog.v1.HolidayR\bholidays\"D\n" +
	"\x14GetCategoriesRequest\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.catalog.v1.CategoryKindR\x04kind\"\x88\x01\n" +
	"\x15GetCategoriesResponse\x124\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x14.catalog.v1.CategoryR\n" +
	"categories\x129\n" +
	"\fbudget_bands\x18\x02 \x03(\v2\x16.catalog.v1.BudgetBandR\vbudgetBands\"V\n" +
	"\rSearchFilters\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12$\n" +
	"\x0ebudget_band_id\x18\x02 \x01(\tR\fbudgetBandId\"\xac\x01\n" +
	"\x18SearchInspirationRequest\x12\x1d\n" +
	"\n" +
	"query_text\x18\x01 \x01(\tR\tqueryText\x12'\n" +
	"\x0fquery_embedding\x18\x02 \x03(\x02R\x0equeryEmbedding\x123\n" +
	"\afilters\x18\x03 \x01(\v2\x19.catalog.v1.SearchFiltersR\afilters\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\"L\n" +
	"\x19SearchInspirationResponse\x12/\n" +
	"\bsnippets\x18\x01 \x03(\v2\x13.catalog.v1.SnippetR\bsnippets\"U\n" +
	"\x18UpsertInspirationRequest\x129\n" +
	"\vinspiration\x18\x01 \x01(\v2\x17.catalog.v1.InspirationR\vinspiration\"+\n" +
	"\x19UpsertInspirationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*R\n" +
	"\bDateRule\x12\x19\n" +
	"\x15DATE_RULE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDATE_RULE_FIXED\x10\x01\x12\x16\n" +
	"\x12DATE_RULE_RELATIVE\x10\x02*]\n" +
	"\fCategoryKind\x12\x1d\n" +
	"\x19CATEGORY_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CATEGORY_KIND_GIFT\x10\x01\x12\x16\n" +
	"\x12CATEGORY_KIND_DATE\x10\x022\xab\x03\n" +
	"\x0eCatalogService\x12g\n" +
	"\fListHolidays\x12\x1f.catalog.v1.ListHolidaysRequest\x1a .catalog.v1.ListHolidaysResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/holidays\x12l\n" +
	"\rGetCategories\x12 .catalog.v1.GetCategoriesRequest\x1a!.catalog.v1.GetCategoriesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/categories\x12`\n" +
	"\x11SearchInspiration\x12$.catalog.v1.SearchInspirationRequest\x1a%.catalog.v1.SearchInspirationResponse\x12`\n" +
	"\x11UpsertInspiration\x12$.catalog.v1.UpsertInspirationRequest\x1a%.catalog.v1.UpsertInspirationResponseB\\ZZgithub.com/ilikyantigran/PerfectGift/services/backend/catalog/pkg/api/catalog/v1;catalogv1b\x06proto3"

var (
	file_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_catalog_v1_catalog_proto_rawDescData []byte
)

func file_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_catalog_v1_catalog_proto_rawDescData
}

var file_catalog_v1_catalog_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_catalog_v1_catalog_proto_goTypes = []any{
	(DateRule)(0),                     // 0: catalog.v1.DateRule
	(CategoryKind)(0),                 // 1: catalog.v1.CategoryKind
	(*Holiday)(nil),                   // 2: catalog.v1.Holiday
	(*Category)(nil),                  // 3: catalog.v1.Category
	(*BudgetBand)(nil),                // 4: catalog.v1.BudgetBand
	(*Inspiration)(nil),               // 5: catalog.v1.Inspiration
	(*Snippet)(nil),                   // 6: catalog.v1.Snippet
	(*ListHolidaysRequest)(nil),       // 7: catalog.v1.ListHolidaysRequest
	(*ListHolidaysResponse)(nil),      // 8: catalog.v1.ListHolidaysResponse
	(*GetCategoriesRequest)(nil),      // 9: catalog.v1.GetCategoriesRequest
	(*GetCategoriesResponse)(nil),     // 10: catalog.v1.GetCategoriesResponse
	(*SearchFilters)(nil),             // 11: catalog.v1.SearchFilters
	(*SearchInspirationRequest)(nil),  // 12: catalog.v1.SearchInspirationRequest
	(*SearchInspirationResponse)(nil), // 13: catalog.v1.SearchInspirationResponse
	(*UpsertInspirationRequest)(nil),  // 14: catalog.v1.UpsertInspirationRequest
	(*UpsertInspirationResponse)(nil), // 15: catalog.v1.UpsertInspirationResponse
}
var file_catalog_v1_catalog_proto_depIdxs = []int32{
	0,  // 0: catalog.v1.Holiday.date_rule:type_name -> catalog.v1.DateRule
	1,  // 1: catalog.v1.Category.kind:type_name -> catalog.v1.CategoryKind
	2,  // 2: catalog.v1.ListHolidaysResponse.holidays:type_name -> catalog.v1.Holiday
	1,  // 3: catalog.v1.GetCategoriesRequest.kind:type_name -> catalog.v1.CategoryKind
	3,  // 4: catalog.v1.GetCategoriesResponse.categories:type_name -> catalog.v1.Category
	4,  // 5: catalog.v1.GetCategoriesResponse.budget_bands:type_name -> catalog.v1.BudgetBand
	11, // 6: catalog.v1.SearchInspirationRequest.filters:type_name -> catalog.v1.SearchFilters
	6,  // 7: catalog.v1.SearchInspirationResponse.snippets:type_name -> catalog.v1.Snippet
	5,  // 8: catalog.v1.UpsertInspirationRequest.inspiration:type_name -> catalog.v1.Inspiration
	7,  // 9: catalog.v1.CatalogService.ListHolidays:input_type -> catalog.v1.ListHolidaysRequest
	9,  // 10: catalog.v1.CatalogService.GetCategories:input_type -> catalog.v1.GetCategoriesRequest
	12, // 11: catalog.v1.CatalogService.SearchInspiration:input_type -> catalog.v1.SearchInspirationRequest
	14, // 12: catalog.v1.CatalogService.UpsertInspiration:input_type -> catalog.v1.UpsertInspirationRequest
	8,  // 13: catalog.v1.CatalogService.ListHolidays:output_type -> catalog.v1.ListHolidaysResponse
	10, // 14: catalog.v1.CatalogService.GetCategories:output_type -> catalog.v1.GetCategoriesResponse
	13, // 15: catalog.v1.CatalogService.SearchInspiration:output_type -> catalog.v1.SearchInspirationResponse
	15, // 16: catalog.v1.CatalogService.UpsertInspiration:output_type -> catalog.v1.UpsertInspirationResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_catalog_v1_catalog_proto_init() }
func file_catalog_v1_catalog_proto_init() {
	if File_catalog_v1_catalog_proto != nil {
		return
	}
	file_catalog_v1_catalog_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_v1_catalog_proto_depIdxs,
		EnumInfos:         file_catalog_v1_catalog_proto_enumTypes,
		MessageInfos:      file_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_catalog_v1_catalog_proto = out.File
	file_catalog_v1_catalog_proto_goTypes = nil
	file_catalog_v1_catalog_proto_depIdxs = nil
}
