// Package docs serves the service's OpenAPI (Swagger) spec and a Swagger UI page.
// The spec is generated by protoc-gen-openapiv2 and copied here by `make generate`,
// then embedded at build time so the binary is self-contained.
package docs

import (
	_ "embed"
	"net/http"
)

//go:embed catalog.swagger.json
var swaggerJSON []byte

const swaggerUI = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>catalog · Swagger UI</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    window.onload = () => {
      window.ui = SwaggerUIBundle({ url: "./swagger.json", dom_id: "#swagger-ui" });
    };
  </script>
</body>
</html>`

// Handler serves the spec at /swagger.json and the UI at /.
func Handler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/swagger.json", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write(swaggerJSON)
	})
	mux.HandleFunc("/", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write([]byte(swaggerUI))
	})
	return mux
}
