// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: surprise/v1/surprise.proto

package surprisev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Surprise_RequestGeneration_FullMethodName   = "/surprise.v1.Surprise/RequestGeneration"
	Surprise_GetGenerationStatus_FullMethodName = "/surprise.v1.Surprise/GetGenerationStatus"
	Surprise_GetIdeas_FullMethodName            = "/surprise.v1.Surprise/GetIdeas"
	Surprise_Refine_FullMethodName              = "/surprise.v1.Surprise/Refine"
	Surprise_SaveIdea_FullMethodName            = "/surprise.v1.Surprise/SaveIdea"
)

// SurpriseClient is the client API for Surprise service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SurpriseClient interface {
	RequestGeneration(ctx context.Context, in *RequestGenerationRequest, opts ...grpc.CallOption) (*RequestGenerationResponse, error)
	GetGenerationStatus(ctx context.Context, in *GetGenerationStatusRequest, opts ...grpc.CallOption) (*GetGenerationStatusResponse, error)
	GetIdeas(ctx context.Context, in *GetIdeasRequest, opts ...grpc.CallOption) (*GetIdeasResponse, error)
	Refine(ctx context.Context, in *RefineRequest, opts ...grpc.CallOption) (*RefineResponse, error)
	SaveIdea(ctx context.Context, in *SaveIdeaRequest, opts ...grpc.CallOption) (*SaveIdeaResponse, error)
}

type surpriseClient struct {
	cc grpc.ClientConnInterface
}

func NewSurpriseClient(cc grpc.ClientConnInterface) SurpriseClient {
	return &surpriseClient{cc}
}

func (c *surpriseClient) RequestGeneration(ctx context.Context, in *RequestGenerationRequest, opts ...grpc.CallOption) (*RequestGenerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestGenerationResponse)
	err := c.cc.Invoke(ctx, Surprise_RequestGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surpriseClient) GetGenerationStatus(ctx context.Context, in *GetGenerationStatusRequest, opts ...grpc.CallOption) (*GetGenerationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGenerationStatusResponse)
	err := c.cc.Invoke(ctx, Surprise_GetGenerationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surpriseClient) GetIdeas(ctx context.Context, in *GetIdeasRequest, opts ...grpc.CallOption) (*GetIdeasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdeasResponse)
	err := c.cc.Invoke(ctx, Surprise_GetIdeas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surpriseClient) Refine(ctx context.Context, in *RefineRequest, opts ...grpc.CallOption) (*RefineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefineResponse)
	err := c.cc.Invoke(ctx, Surprise_Refine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surpriseClient) SaveIdea(ctx context.Context, in *SaveIdeaRequest, opts ...grpc.CallOption) (*SaveIdeaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveIdeaResponse)
	err := c.cc.Invoke(ctx, Surprise_SaveIdea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SurpriseServer is the server API for Surprise service.
// All implementations must embed UnimplementedSurpriseServer
// for forward compatibility.
type SurpriseServer interface {
	RequestGeneration(context.Context, *RequestGenerationRequest) (*RequestGenerationResponse, error)
	GetGenerationStatus(context.Context, *GetGenerationStatusRequest) (*GetGenerationStatusResponse, error)
	GetIdeas(context.Context, *GetIdeasRequest) (*GetIdeasResponse, error)
	Refine(context.Context, *RefineRequest) (*RefineResponse, error)
	SaveIdea(context.Context, *SaveIdeaRequest) (*SaveIdeaResponse, error)
	mustEmbedUnimplementedSurpriseServer()
}

// UnimplementedSurpriseServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSurpriseServer struct{}

func (UnimplementedSurpriseServer) RequestGeneration(context.Context, *RequestGenerationRequest) (*RequestGenerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestGeneration not implemented")
}
func (UnimplementedSurpriseServer) GetGenerationStatus(context.Context, *GetGenerationStatusRequest) (*GetGenerationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGenerationStatus not implemented")
}
func (UnimplementedSurpriseServer) GetIdeas(context.Context, *GetIdeasRequest) (*GetIdeasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdeas not implemented")
}
func (UnimplementedSurpriseServer) Refine(context.Context, *RefineRequest) (*RefineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refine not implemented")
}
func (UnimplementedSurpriseServer) SaveIdea(context.Context, *SaveIdeaRequest) (*SaveIdeaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveIdea not implemented")
}
func (UnimplementedSurpriseServer) mustEmbedUnimplementedSurpriseServer() {}
func (UnimplementedSurpriseServer) testEmbeddedByValue()                  {}

// UnsafeSurpriseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SurpriseServer will
// result in compilation errors.
type UnsafeSurpriseServer interface {
	mustEmbedUnimplementedSurpriseServer()
}

func RegisterSurpriseServer(s grpc.ServiceRegistrar, srv SurpriseServer) {
	// If the following call panics, it indicates UnimplementedSurpriseServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Surprise_ServiceDesc, srv)
}

func _Surprise_RequestGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurpriseServer).RequestGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surprise_RequestGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurpriseServer).RequestGeneration(ctx, req.(*RequestGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surprise_GetGenerationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGenerationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurpriseServer).GetGenerationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surprise_GetGenerationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurpriseServer).GetGenerationStatus(ctx, req.(*GetGenerationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surprise_GetIdeas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdeasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurpriseServer).GetIdeas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surprise_GetIdeas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurpriseServer).GetIdeas(ctx, req.(*GetIdeasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surprise_Refine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurpriseServer).Refine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surprise_Refine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurpriseServer).Refine(ctx, req.(*RefineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surprise_SaveIdea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveIdeaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurpriseServer).SaveIdea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surprise_SaveIdea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurpriseServer).SaveIdea(ctx, req.(*SaveIdeaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Surprise_ServiceDesc is the grpc.ServiceDesc for Surprise service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Surprise_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "surprise.v1.Surprise",
	HandlerType: (*SurpriseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestGeneration",
			Handler:    _Surprise_RequestGeneration_Handler,
		},
		{
			MethodName: "GetGenerationStatus",
			Handler:    _Surprise_GetGenerationStatus_Handler,
		},
		{
			MethodName: "GetIdeas",
			Handler:    _Surprise_GetIdeas_Handler,
		},
		{
			MethodName: "Refine",
			Handler:    _Surprise_Refine_Handler,
		},
		{
			MethodName: "SaveIdea",
			Handler:    _Surprise_SaveIdea_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "surprise/v1/surprise.proto",
}
