// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: surprise/v1/surprise.proto

package surprisev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// user_id is injected by the gateway from the JWT subject, not the body.
type RequestGenerationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HolidayId       string                 `protobuf:"bytes,2,opt,name=holiday_id,json=holidayId,proto3" json:"holiday_id,omitempty"`
	BudgetBand      string                 `protobuf:"bytes,3,opt,name=budget_band,json=budgetBand,proto3" json:"budget_band,omitempty"`
	PreferencesText string                 `protobuf:"bytes,4,opt,name=preferences_text,json=preferencesText,proto3" json:"preferences_text,omitempty"`
	PollId          string                 `protobuf:"bytes,5,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Tier            string                 `protobuf:"bytes,6,opt,name=tier,proto3" json:"tier,omitempty"`                                           // sonnet (default) | opus | haiku
	IdempotencyKey  string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // forwarded from the Idempotency-Key header
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestGenerationRequest) Reset() {
	*x = RequestGenerationRequest{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGenerationRequest) ProtoMessage() {}

func (x *RequestGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGenerationRequest.ProtoReflect.Descriptor instead.
func (*RequestGenerationRequest) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{0}
}

func (x *RequestGenerationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestGenerationRequest) GetHolidayId() string {
	if x != nil {
		return x.HolidayId
	}
	return ""
}

func (x *RequestGenerationRequest) GetBudgetBand() string {
	if x != nil {
		return x.BudgetBand
	}
	return ""
}

func (x *RequestGenerationRequest) GetPreferencesText() string {
	if x != nil {
		return x.PreferencesText
	}
	return ""
}

func (x *RequestGenerationRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *RequestGenerationRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *RequestGenerationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type RequestGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // queued
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGenerationResponse) Reset() {
	*x = RequestGenerationResponse{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGenerationResponse) ProtoMessage() {}

func (x *RequestGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGenerationResponse.ProtoReflect.Descriptor instead.
func (*RequestGenerationResponse) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{1}
}

func (x *RequestGenerationResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestGenerationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetGenerationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenerationStatusRequest) Reset() {
	*x = GetGenerationStatusRequest{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenerationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerationStatusRequest) ProtoMessage() {}

func (x *GetGenerationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetGenerationStatusRequest) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{2}
}

func (x *GetGenerationStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetGenerationStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetGenerationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // queued | running | ready | failed
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenerationStatusResponse) Reset() {
	*x = GetGenerationStatusResponse{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenerationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerationStatusResponse) ProtoMessage() {}

func (x *GetGenerationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetGenerationStatusResponse) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{3}
}

func (x *GetGenerationStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetGenerationStatusResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type Idea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	WhyItFits     string                 `protobuf:"bytes,3,opt,name=why_it_fits,json=whyItFits,proto3" json:"why_it_fits,omitempty"`
	RoughCost     string                 `protobuf:"bytes,4,opt,name=rough_cost,json=roughCost,proto3" json:"rough_cost,omitempty"`
	HowTo         string                 `protobuf:"bytes,5,opt,name=how_to,json=howTo,proto3" json:"how_to,omitempty"`
	Rank          int32                  `protobuf:"varint,6,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Idea) Reset() {
	*x = Idea{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Idea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idea) ProtoMessage() {}

func (x *Idea) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idea.ProtoReflect.Descriptor instead.
func (*Idea) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{4}
}

func (x *Idea) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Idea) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Idea) GetWhyItFits() string {
	if x != nil {
		return x.WhyItFits
	}
	return ""
}

func (x *Idea) GetRoughCost() string {
	if x != nil {
		return x.RoughCost
	}
	return ""
}

func (x *Idea) GetHowTo() string {
	if x != nil {
		return x.HowTo
	}
	return ""
}

func (x *Idea) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type GetIdeasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdeasRequest) Reset() {
	*x = GetIdeasRequest{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdeasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdeasRequest) ProtoMessage() {}

func (x *GetIdeasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdeasRequest.ProtoReflect.Descriptor instead.
func (*GetIdeasRequest) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{5}
}

func (x *GetIdeasRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetIdeasRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetIdeasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ideas         []*Idea                `protobuf:"bytes,1,rep,name=ideas,proto3" json:"ideas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdeasResponse) Reset() {
	*x = GetIdeasResponse{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdeasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdeasResponse) ProtoMessage() {}

func (x *GetIdeasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdeasResponse.ProtoReflect.Descriptor instead.
func (*GetIdeasResponse) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{6}
}

func (x *GetIdeasResponse) GetIdeas() []*Idea {
	if x != nil {
		return x.Ideas
	}
	return nil
}

type RefineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Refinement    string                 `protobuf:"bytes,3,opt,name=refinement,proto3" json:"refinement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefineRequest) Reset() {
	*x = RefineRequest{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefineRequest) ProtoMessage() {}

func (x *RefineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefineRequest.ProtoReflect.Descriptor instead.
func (*RefineRequest) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{7}
}

func (x *RefineRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RefineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefineRequest) GetRefinement() string {
	if x != nil {
		return x.Refinement
	}
	return ""
}

type RefineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // queued
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefineResponse) Reset() {
	*x = RefineResponse{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefineResponse) ProtoMessage() {}

func (x *RefineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefineResponse.ProtoReflect.Descriptor instead.
func (*RefineResponse) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{8}
}

func (x *RefineResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RefineResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SaveIdeaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdeaId        string                 `protobuf:"bytes,2,opt,name=idea_id,json=ideaId,proto3" json:"idea_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveIdeaRequest) Reset() {
	*x = SaveIdeaRequest{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveIdeaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveIdeaRequest) ProtoMessage() {}

func (x *SaveIdeaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveIdeaRequest.ProtoReflect.Descriptor instead.
func (*SaveIdeaRequest) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{9}
}

func (x *SaveIdeaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveIdeaRequest) GetIdeaId() string {
	if x != nil {
		return x.IdeaId
	}
	return ""
}

type SaveIdeaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveIdeaResponse) Reset() {
	*x = SaveIdeaResponse{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveIdeaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveIdeaResponse) ProtoMessage() {}

func (x *SaveIdeaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveIdeaResponse.ProtoReflect.Descriptor instead.
func (*SaveIdeaResponse) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{10}
}

func (x *SaveIdeaResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_surprise_v1_surprise_proto protoreflect.FileDescriptor

const file_surprise_v1_surprise_proto_rawDesc = "" +
	"\n" +
	"\x1asurprise/v1/surprise.proto\x12\vsurprise.v1\"\xf4\x01\n" +
	"\x18RequestGenerationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"holiday_id\x18\x02 \x01(\tR\tholidayId\x12\x1f\n" +
	"\vbudget_band\x18\x03 \x01(\tR\n" +
	"budgetBand\x12)\n" +
	"\x10preferences_text\x18\x04 \x01(\tR\x0fpreferencesText\x12\x17\n" +
	"\apoll_id\x18\x05 \x01(\tR\x06pollId\x12\x12\n" +
	"\x04tier\x18\x06 \x01(\tR\x04tier\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"R\n" +
	"\x19RequestGenerationResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"T\n" +
	"\x1aGetGenerationStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"Q\n" +
	"\x1bGetGenerationStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\"\x96\x01\n" +
	"\x04Idea\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\vwhy_it_fits\x18\x03 \x01(\tR\twhyItFits\x12\x1d\n" +
	"\n" +
	"rough_cost\x18\x04 \x01(\tR\troughCost\x12\x15\n" +
	"\x06how_to\x18\x05 \x01(\tR\x05howTo\x12\x12\n" +
	"\x04rank\x18\x06 \x01(\x05R\x04rank\"I\n" +
	"\x0fGetIdeasRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\";\n" +
	"\x10GetIdeasResponse\x12'\n" +
	"\x05ideas\x18\x01 \x03(\v2\x11.surprise.v1.IdeaR\x05ideas\"g\n" +
	"\rRefineRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"refinement\x18\x03 \x01(\tR\n" +
	"refinement\"G\n" +
	"\x0eRefineResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"C\n" +
	"\x0fSaveIdeaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aidea_id\x18\x02 \x01(\tR\x06ideaId\"\"\n" +
	"\x10SaveIdeaResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xad\x03\n" +
	"\bSurprise\x12b\n" +
	"\x11RequestGeneration\x12%.surprise.v1.RequestGenerationRequest\x1a&.surprise.v1.RequestGenerationResponse\x12h\n" +
	"\x13GetGenerationStatus\x12'.surprise.v1.GetGenerationStatusRequest\x1a(.surprise.v1.GetGenerationStatusResponse\x12G\n" +
	"\bGetIdeas\x12\x1c.surprise.v1.GetIdeasRequest\x1a\x1d.surprise.v1.GetIdeasResponse\x12A\n" +
	"\x06Refine\x12\x1a.surprise.v1.RefineRequest\x1a\x1b.surprise.v1.RefineResponse\x12G\n" +
	"\bSaveIdea\x12\x1c.surprise.v1.SaveIdeaRequest\x1a\x1d.surprise.v1.SaveIdeaResponseBbZ`github.com/ilikyantigran/PerfectGift/services/backend/api-gateway/pkg/api/surprise/v1;surprisev1b\x06proto3"

var (
	file_surprise_v1_surprise_proto_rawDescOnce sync.Once
	file_surprise_v1_surprise_proto_rawDescData []byte
)

func file_surprise_v1_surprise_proto_rawDescGZIP() []byte {
	file_surprise_v1_surprise_proto_rawDescOnce.Do(func() {
		file_surprise_v1_surprise_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_surprise_v1_surprise_proto_rawDesc), len(file_surprise_v1_surprise_proto_rawDesc)))
	})
	return file_surprise_v1_surprise_proto_rawDescData
}

var file_surprise_v1_surprise_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_surprise_v1_surprise_proto_goTypes = []any{
	(*RequestGenerationRequest)(nil),    // 0: surprise.v1.RequestGenerationRequest
	(*RequestGenerationResponse)(nil),   // 1: surprise.v1.RequestGenerationResponse
	(*GetGenerationStatusRequest)(nil),  // 2: surprise.v1.GetGenerationStatusRequest
	(*GetGenerationStatusResponse)(nil), // 3: surprise.v1.GetGenerationStatusResponse
	(*Idea)(nil),                        // 4: surprise.v1.Idea
	(*GetIdeasRequest)(nil),             // 5: surprise.v1.GetIdeasRequest
	(*GetIdeasResponse)(nil),            // 6: surprise.v1.GetIdeasResponse
	(*RefineRequest)(nil),               // 7: surprise.v1.RefineRequest
	(*RefineResponse)(nil),              // 8: surprise.v1.RefineResponse
	(*SaveIdeaRequest)(nil),             // 9: surprise.v1.SaveIdeaRequest
	(*SaveIdeaResponse)(nil),            // 10: surprise.v1.SaveIdeaResponse
}
var file_surprise_v1_surprise_proto_depIdxs = []int32{
	4,  // 0: surprise.v1.GetIdeasResponse.ideas:type_name -> surprise.v1.Idea
	0,  // 1: surprise.v1.Surprise.RequestGeneration:input_type -> surprise.v1.RequestGenerationRequest
	2,  // 2: surprise.v1.Surprise.GetGenerationStatus:input_type -> surprise.v1.GetGenerationStatusRequest
	5,  // 3: surprise.v1.Surprise.GetIdeas:input_type -> surprise.v1.GetIdeasRequest
	7,  // 4: surprise.v1.Surprise.Refine:input_type -> surprise.v1.RefineRequest
	9,  // 5: surprise.v1.Surprise.SaveIdea:input_type -> surprise.v1.SaveIdeaRequest
	1,  // 6: surprise.v1.Surprise.RequestGeneration:output_type -> surprise.v1.RequestGenerationResponse
	3,  // 7: surprise.v1.Surprise.GetGenerationStatus:output_type -> surprise.v1.GetGenerationStatusResponse
	6,  // 8: surprise.v1.Surprise.GetIdeas:output_type -> surprise.v1.GetIdeasResponse
	8,  // 9: surprise.v1.Surprise.Refine:output_type -> surprise.v1.RefineResponse
	10, // 10: surprise.v1.Surprise.SaveIdea:output_type -> surprise.v1.SaveIdeaResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_surprise_v1_surprise_proto_init() }
func file_surprise_v1_surprise_proto_init() {
	if File_surprise_v1_surprise_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_surprise_v1_surprise_proto_rawDesc), len(file_surprise_v1_surprise_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_surprise_v1_surprise_proto_goTypes,
		DependencyIndexes: file_surprise_v1_surprise_proto_depIdxs,
		MessageInfos:      file_surprise_v1_surprise_proto_msgTypes,
	}.Build()
	File_surprise_v1_surprise_proto = out.File
	file_surprise_v1_surprise_proto_goTypes = nil
	file_surprise_v1_surprise_proto_depIdxs = nil
}
