// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: catalog/v1/catalog.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Holiday struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DateRule      string                 `protobuf:"bytes,3,opt,name=date_rule,json=dateRule,proto3" json:"date_rule,omitempty"` // fixed | relative
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Holiday) Reset() {
	*x = Holiday{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holiday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holiday) ProtoMessage() {}

func (x *Holiday) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holiday.ProtoReflect.Descriptor instead.
func (*Holiday) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Holiday) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Holiday) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Holiday) GetDateRule() string {
	if x != nil {
		return x.DateRule
	}
	return ""
}

func (x *Holiday) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Holiday) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Holiday) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type ListHolidaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	OnOrAfter     string                 `protobuf:"bytes,3,opt,name=on_or_after,json=onOrAfter,proto3" json:"on_or_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHolidaysRequest) Reset() {
	*x = ListHolidaysRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHolidaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHolidaysRequest) ProtoMessage() {}

func (x *ListHolidaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHolidaysRequest.ProtoReflect.Descriptor instead.
func (*ListHolidaysRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ListHolidaysRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ListHolidaysRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ListHolidaysRequest) GetOnOrAfter() string {
	if x != nil {
		return x.OnOrAfter
	}
	return ""
}

type ListHolidaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holidays      []*Holiday             `protobuf:"bytes,1,rep,name=holidays,proto3" json:"holidays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHolidaysResponse) Reset() {
	*x = ListHolidaysResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHolidaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHolidaysResponse) ProtoMessage() {}

func (x *ListHolidaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHolidaysResponse.ProtoReflect.Descriptor instead.
func (*ListHolidaysResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ListHolidaysResponse) GetHolidays() []*Holiday {
	if x != nil {
		return x.Holidays
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // gift | date
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Category) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type BudgetBand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Min           int64                  `protobuf:"varint,3,opt,name=min,proto3" json:"min,omitempty"`
	Max           int64                  `protobuf:"varint,4,opt,name=max,proto3" json:"max,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetBand) Reset() {
	*x = BudgetBand{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetBand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetBand) ProtoMessage() {}

func (x *BudgetBand) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetBand.ProtoReflect.Descriptor instead.
func (*BudgetBand) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *BudgetBand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BudgetBand) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BudgetBand) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *BudgetBand) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *BudgetBand) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesRequest) Reset() {
	*x = GetCategoriesRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesRequest) ProtoMessage() {}

func (x *GetCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetCategoriesRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type GetCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	BudgetBands   []*BudgetBand          `protobuf:"bytes,2,rep,name=budget_bands,json=budgetBands,proto3" json:"budget_bands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetCategoriesResponse) GetBudgetBands() []*BudgetBand {
	if x != nil {
		return x.BudgetBands
	}
	return nil
}

var File_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/v1/catalog.proto\x12\n" +
	"catalog.v1\"\x8e\x01\n" +
	"\aHoliday\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tdate_rule\x18\x03 \x01(\tR\bdateRule\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\"e\n" +
	"\x13ListHolidaysRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x1e\n" +
	"\von_or_after\x18\x03 \x01(\tR\tonOrAfter\"G\n" +
	"\x14ListHolidaysResponse\x12/\n" +
	"\bholidays\x18\x01 \x03(\v2\x13.catalog.v1.HolidayR\bholidays\"_\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\"r\n" +
	"\n" +
	"BudgetBand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x10\n" +
	"\x03min\x18\x03 \x01(\x03R\x03min\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x03R\x03max\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"*\n" +
	"\x14GetCategoriesRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"\x88\x01\n" +
	"\x15GetCategoriesResponse\x124\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x14.catalog.v1.CategoryR\n" +
	"categories\x129\n" +
	"\fbudget_bands\x18\x02 \x03(\v2\x16.catalog.v1.BudgetBandR\vbudgetBands2\xb2\x01\n" +
	"\aCatalog\x12Q\n" +
	"\fListHolidays\x12\x1f.catalog.v1.ListHolidaysRequest\x1a .catalog.v1.ListHolidaysResponse\x12T\n" +
	"\rGetCategories\x12 .catalog.v1.GetCategoriesRequest\x1a!.catalog.v1.GetCategoriesResponseB`Z^github.com/ilikyantigran/PerfectGift/services/backend/api-gateway/pkg/api/catalog/v1;catalogv1b\x06proto3"

var (
	file_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_catalog_v1_catalog_proto_rawDescData []byte
)

func file_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_catalog_v1_catalog_proto_rawDescData
}

var file_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_catalog_v1_catalog_proto_goTypes = []any{
	(*Holiday)(nil),               // 0: catalog.v1.Holiday
	(*ListHolidaysRequest)(nil),   // 1: catalog.v1.ListHolidaysRequest
	(*ListHolidaysResponse)(nil),  // 2: catalog.v1.ListHolidaysResponse
	(*Category)(nil),              // 3: catalog.v1.Category
	(*BudgetBand)(nil),            // 4: catalog.v1.BudgetBand
	(*GetCategoriesRequest)(nil),  // 5: catalog.v1.GetCategoriesRequest
	(*GetCategoriesResponse)(nil), // 6: catalog.v1.GetCategoriesResponse
}
var file_catalog_v1_catalog_proto_depIdxs = []int32{
	0, // 0: catalog.v1.ListHolidaysResponse.holidays:type_name -> catalog.v1.Holiday
	3, // 1: catalog.v1.GetCategoriesResponse.categories:type_name -> catalog.v1.Category
	4, // 2: catalog.v1.GetCategoriesResponse.budget_bands:type_name -> catalog.v1.BudgetBand
	1, // 3: catalog.v1.Catalog.ListHolidays:input_type -> catalog.v1.ListHolidaysRequest
	5, // 4: catalog.v1.Catalog.GetCategories:input_type -> catalog.v1.GetCategoriesRequest
	2, // 5: catalog.v1.Catalog.ListHolidays:output_type -> catalog.v1.ListHolidaysResponse
	6, // 6: catalog.v1.Catalog.GetCategories:output_type -> catalog.v1.GetCategoriesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_catalog_v1_catalog_proto_init() }
func file_catalog_v1_catalog_proto_init() {
	if File_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_catalog_v1_catalog_proto = out.File
	file_catalog_v1_catalog_proto_goTypes = nil
	file_catalog_v1_catalog_proto_depIdxs = nil
}
