// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: surprise/v1/surprise.proto

package surprisev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SurpriseService_RequestGeneration_FullMethodName   = "/surprise.v1.SurpriseService/RequestGeneration"
	SurpriseService_GetGenerationStatus_FullMethodName = "/surprise.v1.SurpriseService/GetGenerationStatus"
	SurpriseService_GetIdeas_FullMethodName            = "/surprise.v1.SurpriseService/GetIdeas"
	SurpriseService_SaveIdea_FullMethodName            = "/surprise.v1.SurpriseService/SaveIdea"
	SurpriseService_Refine_FullMethodName              = "/surprise.v1.SurpriseService/Refine"
)

// SurpriseServiceClient is the client API for SurpriseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SurpriseService orchestrates async LLM idea generation. Lifecycle RPCs on the
// request path are fast (persist + enqueue); the slow LLM work runs in a worker
// pool that consumes the GenerationRequested job off NATS.
type SurpriseServiceClient interface {
	// RequestGeneration persists the request (idempotency-keyed) and enqueues a job,
	// then returns immediately. Maps to HTTP 202.
	RequestGeneration(ctx context.Context, in *RequestGenerationRequest, opts ...grpc.CallOption) (*RequestGenerationResponse, error)
	// GetGenerationStatus is a cheap poll target backed by Valkey.
	GetGenerationStatus(ctx context.Context, in *GetGenerationStatusRequest, opts ...grpc.CallOption) (*GetGenerationStatusResponse, error)
	// GetIdeas returns the ranked ideas for a request. Empty until status is READY.
	GetIdeas(ctx context.Context, in *GetIdeasRequest, opts ...grpc.CallOption) (*GetIdeasResponse, error)
	// SaveIdea favorites/saves an idea for the caller.
	SaveIdea(ctx context.Context, in *SaveIdeaRequest, opts ...grpc.CallOption) (*SaveIdeaResponse, error)
	// Refine regenerates with adjustments (a new job on the same request).
	Refine(ctx context.Context, in *RefineRequest, opts ...grpc.CallOption) (*RefineResponse, error)
}

type surpriseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSurpriseServiceClient(cc grpc.ClientConnInterface) SurpriseServiceClient {
	return &surpriseServiceClient{cc}
}

func (c *surpriseServiceClient) RequestGeneration(ctx context.Context, in *RequestGenerationRequest, opts ...grpc.CallOption) (*RequestGenerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestGenerationResponse)
	err := c.cc.Invoke(ctx, SurpriseService_RequestGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surpriseServiceClient) GetGenerationStatus(ctx context.Context, in *GetGenerationStatusRequest, opts ...grpc.CallOption) (*GetGenerationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGenerationStatusResponse)
	err := c.cc.Invoke(ctx, SurpriseService_GetGenerationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surpriseServiceClient) GetIdeas(ctx context.Context, in *GetIdeasRequest, opts ...grpc.CallOption) (*GetIdeasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdeasResponse)
	err := c.cc.Invoke(ctx, SurpriseService_GetIdeas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surpriseServiceClient) SaveIdea(ctx context.Context, in *SaveIdeaRequest, opts ...grpc.CallOption) (*SaveIdeaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveIdeaResponse)
	err := c.cc.Invoke(ctx, SurpriseService_SaveIdea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surpriseServiceClient) Refine(ctx context.Context, in *RefineRequest, opts ...grpc.CallOption) (*RefineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefineResponse)
	err := c.cc.Invoke(ctx, SurpriseService_Refine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SurpriseServiceServer is the server API for SurpriseService service.
// All implementations must embed UnimplementedSurpriseServiceServer
// for forward compatibility.
//
// SurpriseService orchestrates async LLM idea generation. Lifecycle RPCs on the
// request path are fast (persist + enqueue); the slow LLM work runs in a worker
// pool that consumes the GenerationRequested job off NATS.
type SurpriseServiceServer interface {
	// RequestGeneration persists the request (idempotency-keyed) and enqueues a job,
	// then returns immediately. Maps to HTTP 202.
	RequestGeneration(context.Context, *RequestGenerationRequest) (*RequestGenerationResponse, error)
	// GetGenerationStatus is a cheap poll target backed by Valkey.
	GetGenerationStatus(context.Context, *GetGenerationStatusRequest) (*GetGenerationStatusResponse, error)
	// GetIdeas returns the ranked ideas for a request. Empty until status is READY.
	GetIdeas(context.Context, *GetIdeasRequest) (*GetIdeasResponse, error)
	// SaveIdea favorites/saves an idea for the caller.
	SaveIdea(context.Context, *SaveIdeaRequest) (*SaveIdeaResponse, error)
	// Refine regenerates with adjustments (a new job on the same request).
	Refine(context.Context, *RefineRequest) (*RefineResponse, error)
	mustEmbedUnimplementedSurpriseServiceServer()
}

// UnimplementedSurpriseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSurpriseServiceServer struct{}

func (UnimplementedSurpriseServiceServer) RequestGeneration(context.Context, *RequestGenerationRequest) (*RequestGenerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestGeneration not implemented")
}
func (UnimplementedSurpriseServiceServer) GetGenerationStatus(context.Context, *GetGenerationStatusRequest) (*GetGenerationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGenerationStatus not implemented")
}
func (UnimplementedSurpriseServiceServer) GetIdeas(context.Context, *GetIdeasRequest) (*GetIdeasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIdeas not implemented")
}
func (UnimplementedSurpriseServiceServer) SaveIdea(context.Context, *SaveIdeaRequest) (*SaveIdeaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveIdea not implemented")
}
func (UnimplementedSurpriseServiceServer) Refine(context.Context, *RefineRequest) (*RefineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refine not implemented")
}
func (UnimplementedSurpriseServiceServer) mustEmbedUnimplementedSurpriseServiceServer() {}
func (UnimplementedSurpriseServiceServer) testEmbeddedByValue()                         {}

// UnsafeSurpriseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SurpriseServiceServer will
// result in compilation errors.
type UnsafeSurpriseServiceServer interface {
	mustEmbedUnimplementedSurpriseServiceServer()
}

func RegisterSurpriseServiceServer(s grpc.ServiceRegistrar, srv SurpriseServiceServer) {
	// If the following call panics, it indicates UnimplementedSurpriseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SurpriseService_ServiceDesc, srv)
}

func _SurpriseService_RequestGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurpriseServiceServer).RequestGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurpriseService_RequestGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurpriseServiceServer).RequestGeneration(ctx, req.(*RequestGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SurpriseService_GetGenerationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGenerationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurpriseServiceServer).GetGenerationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurpriseService_GetGenerationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurpriseServiceServer).GetGenerationStatus(ctx, req.(*GetGenerationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SurpriseService_GetIdeas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdeasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurpriseServiceServer).GetIdeas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurpriseService_GetIdeas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurpriseServiceServer).GetIdeas(ctx, req.(*GetIdeasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SurpriseService_SaveIdea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveIdeaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurpriseServiceServer).SaveIdea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurpriseService_SaveIdea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurpriseServiceServer).SaveIdea(ctx, req.(*SaveIdeaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SurpriseService_Refine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurpriseServiceServer).Refine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SurpriseService_Refine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurpriseServiceServer).Refine(ctx, req.(*RefineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SurpriseService_ServiceDesc is the grpc.ServiceDesc for SurpriseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SurpriseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "surprise.v1.SurpriseService",
	HandlerType: (*SurpriseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestGeneration",
			Handler:    _SurpriseService_RequestGeneration_Handler,
		},
		{
			MethodName: "GetGenerationStatus",
			Handler:    _SurpriseService_GetGenerationStatus_Handler,
		},
		{
			MethodName: "GetIdeas",
			Handler:    _SurpriseService_GetIdeas_Handler,
		},
		{
			MethodName: "SaveIdea",
			Handler:    _SurpriseService_SaveIdea_Handler,
		},
		{
			MethodName: "Refine",
			Handler:    _SurpriseService_Refine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "surprise/v1/surprise.proto",
}
