// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: surprise/v1/surprise.proto

package surprisev1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerationStatus is the lifecycle of a generation request.
type GenerationStatus int32

const (
	GenerationStatus_GENERATION_STATUS_UNSPECIFIED GenerationStatus = 0
	GenerationStatus_GENERATION_STATUS_QUEUED      GenerationStatus = 1
	GenerationStatus_GENERATION_STATUS_RUNNING     GenerationStatus = 2
	GenerationStatus_GENERATION_STATUS_READY       GenerationStatus = 3
	GenerationStatus_GENERATION_STATUS_FAILED      GenerationStatus = 4
)

// Enum value maps for GenerationStatus.
var (
	GenerationStatus_name = map[int32]string{
		0: "GENERATION_STATUS_UNSPECIFIED",
		1: "GENERATION_STATUS_QUEUED",
		2: "GENERATION_STATUS_RUNNING",
		3: "GENERATION_STATUS_READY",
		4: "GENERATION_STATUS_FAILED",
	}
	GenerationStatus_value = map[string]int32{
		"GENERATION_STATUS_UNSPECIFIED": 0,
		"GENERATION_STATUS_QUEUED":      1,
		"GENERATION_STATUS_RUNNING":     2,
		"GENERATION_STATUS_READY":       3,
		"GENERATION_STATUS_FAILED":      4,
	}
)

func (x GenerationStatus) Enum() *GenerationStatus {
	p := new(GenerationStatus)
	*p = x
	return p
}

func (x GenerationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_surprise_v1_surprise_proto_enumTypes[0].Descriptor()
}

func (GenerationStatus) Type() protoreflect.EnumType {
	return &file_surprise_v1_surprise_proto_enumTypes[0]
}

func (x GenerationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerationStatus.Descriptor instead.
func (GenerationStatus) EnumDescriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{0}
}

// ModelTier selects the generation model. Sonnet is the default; Opus is the
// premium/"deep" tier. (Haiku is used internally for moderation, not selectable here.)
type ModelTier int32

const (
	ModelTier_MODEL_TIER_UNSPECIFIED ModelTier = 0
	ModelTier_MODEL_TIER_SONNET      ModelTier = 1
	ModelTier_MODEL_TIER_OPUS        ModelTier = 2
)

// Enum value maps for ModelTier.
var (
	ModelTier_name = map[int32]string{
		0: "MODEL_TIER_UNSPECIFIED",
		1: "MODEL_TIER_SONNET",
		2: "MODEL_TIER_OPUS",
	}
	ModelTier_value = map[string]int32{
		"MODEL_TIER_UNSPECIFIED": 0,
		"MODEL_TIER_SONNET":      1,
		"MODEL_TIER_OPUS":        2,
	}
)

func (x ModelTier) Enum() *ModelTier {
	p := new(ModelTier)
	*p = x
	return p
}

func (x ModelTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelTier) Descriptor() protoreflect.EnumDescriptor {
	return file_surprise_v1_surprise_proto_enumTypes[1].Descriptor()
}

func (ModelTier) Type() protoreflect.EnumType {
	return &file_surprise_v1_surprise_proto_enumTypes[1]
}

func (x ModelTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelTier.Descriptor instead.
func (ModelTier) EnumDescriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{1}
}

// ModerationStatus is the outcome of the Haiku moderation pass on an idea.
type ModerationStatus int32

const (
	ModerationStatus_MODERATION_STATUS_UNSPECIFIED ModerationStatus = 0
	ModerationStatus_MODERATION_STATUS_APPROVED    ModerationStatus = 1
	ModerationStatus_MODERATION_STATUS_REJECTED    ModerationStatus = 2
)

// Enum value maps for ModerationStatus.
var (
	ModerationStatus_name = map[int32]string{
		0: "MODERATION_STATUS_UNSPECIFIED",
		1: "MODERATION_STATUS_APPROVED",
		2: "MODERATION_STATUS_REJECTED",
	}
	ModerationStatus_value = map[string]int32{
		"MODERATION_STATUS_UNSPECIFIED": 0,
		"MODERATION_STATUS_APPROVED":    1,
		"MODERATION_STATUS_REJECTED":    2,
	}
)

func (x ModerationStatus) Enum() *ModerationStatus {
	p := new(ModerationStatus)
	*p = x
	return p
}

func (x ModerationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModerationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_surprise_v1_surprise_proto_enumTypes[2].Descriptor()
}

func (ModerationStatus) Type() protoreflect.EnumType {
	return &file_surprise_v1_surprise_proto_enumTypes[2]
}

func (x ModerationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModerationStatus.Descriptor instead.
func (ModerationStatus) EnumDescriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{2}
}

type RequestGenerationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HolidayId       string                 `protobuf:"bytes,2,opt,name=holiday_id,json=holidayId,proto3" json:"holiday_id,omitempty"`
	BudgetBand      string                 `protobuf:"bytes,3,opt,name=budget_band,json=budgetBand,proto3" json:"budget_band,omitempty"`
	PreferencesText string                 `protobuf:"bytes,4,opt,name=preferences_text,json=preferencesText,proto3" json:"preferences_text,omitempty"`
	PollId          string                 `protobuf:"bytes,5,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`           // optional
	Tier            ModelTier              `protobuf:"varint,6,opt,name=tier,proto3,enum=surprise.v1.ModelTier" json:"tier,omitempty"` // optional; defaults to SONNET
	IdempotencyKey  string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestGenerationRequest) Reset() {
	*x = RequestGenerationRequest{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGenerationRequest) ProtoMessage() {}

func (x *RequestGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGenerationRequest.ProtoReflect.Descriptor instead.
func (*RequestGenerationRequest) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{0}
}

func (x *RequestGenerationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestGenerationRequest) GetHolidayId() string {
	if x != nil {
		return x.HolidayId
	}
	return ""
}

func (x *RequestGenerationRequest) GetBudgetBand() string {
	if x != nil {
		return x.BudgetBand
	}
	return ""
}

func (x *RequestGenerationRequest) GetPreferencesText() string {
	if x != nil {
		return x.PreferencesText
	}
	return ""
}

func (x *RequestGenerationRequest) GetPollId() string {
	if x != nil {
		return x.PollId
	}
	return ""
}

func (x *RequestGenerationRequest) GetTier() ModelTier {
	if x != nil {
		return x.Tier
	}
	return ModelTier_MODEL_TIER_UNSPECIFIED
}

func (x *RequestGenerationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type RequestGenerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        GenerationStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=surprise.v1.GenerationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGenerationResponse) Reset() {
	*x = RequestGenerationResponse{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGenerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGenerationResponse) ProtoMessage() {}

func (x *RequestGenerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGenerationResponse.ProtoReflect.Descriptor instead.
func (*RequestGenerationResponse) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{1}
}

func (x *RequestGenerationResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestGenerationResponse) GetStatus() GenerationStatus {
	if x != nil {
		return x.Status
	}
	return GenerationStatus_GENERATION_STATUS_UNSPECIFIED
}

type GetGenerationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenerationStatusRequest) Reset() {
	*x = GetGenerationStatusRequest{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenerationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerationStatusRequest) ProtoMessage() {}

func (x *GetGenerationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetGenerationStatusRequest) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{2}
}

func (x *GetGenerationStatusRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetGenerationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        GenerationStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=surprise.v1.GenerationStatus" json:"status,omitempty"`
	Progress      uint32                 `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"` // 0..100, best-effort
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenerationStatusResponse) Reset() {
	*x = GetGenerationStatusResponse{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenerationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerationStatusResponse) ProtoMessage() {}

func (x *GetGenerationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetGenerationStatusResponse) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{3}
}

func (x *GetGenerationStatusResponse) GetStatus() GenerationStatus {
	if x != nil {
		return x.Status
	}
	return GenerationStatus_GENERATION_STATUS_UNSPECIFIED
}

func (x *GetGenerationStatusResponse) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type GetIdeasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdeasRequest) Reset() {
	*x = GetIdeasRequest{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdeasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdeasRequest) ProtoMessage() {}

func (x *GetIdeasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdeasRequest.ProtoReflect.Descriptor instead.
func (*GetIdeasRequest) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{4}
}

func (x *GetIdeasRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Idea is a single generated surprise idea (typed, not prose).
type Idea struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId        string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	WhyItFits        string                 `protobuf:"bytes,4,opt,name=why_it_fits,json=whyItFits,proto3" json:"why_it_fits,omitempty"`
	RoughCost        string                 `protobuf:"bytes,5,opt,name=rough_cost,json=roughCost,proto3" json:"rough_cost,omitempty"`
	HowTo            string                 `protobuf:"bytes,6,opt,name=how_to,json=howTo,proto3" json:"how_to,omitempty"`
	Rank             uint32                 `protobuf:"varint,7,opt,name=rank,proto3" json:"rank,omitempty"`
	ModerationStatus ModerationStatus       `protobuf:"varint,8,opt,name=moderation_status,json=moderationStatus,proto3,enum=surprise.v1.ModerationStatus" json:"moderation_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Idea) Reset() {
	*x = Idea{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Idea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idea) ProtoMessage() {}

func (x *Idea) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idea.ProtoReflect.Descriptor instead.
func (*Idea) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{5}
}

func (x *Idea) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Idea) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Idea) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Idea) GetWhyItFits() string {
	if x != nil {
		return x.WhyItFits
	}
	return ""
}

func (x *Idea) GetRoughCost() string {
	if x != nil {
		return x.RoughCost
	}
	return ""
}

func (x *Idea) GetHowTo() string {
	if x != nil {
		return x.HowTo
	}
	return ""
}

func (x *Idea) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Idea) GetModerationStatus() ModerationStatus {
	if x != nil {
		return x.ModerationStatus
	}
	return ModerationStatus_MODERATION_STATUS_UNSPECIFIED
}

type GetIdeasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ideas         []*Idea                `protobuf:"bytes,1,rep,name=ideas,proto3" json:"ideas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdeasResponse) Reset() {
	*x = GetIdeasResponse{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdeasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdeasResponse) ProtoMessage() {}

func (x *GetIdeasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdeasResponse.ProtoReflect.Descriptor instead.
func (*GetIdeasResponse) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{6}
}

func (x *GetIdeasResponse) GetIdeas() []*Idea {
	if x != nil {
		return x.Ideas
	}
	return nil
}

type SaveIdeaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdeaId        string                 `protobuf:"bytes,2,opt,name=idea_id,json=ideaId,proto3" json:"idea_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveIdeaRequest) Reset() {
	*x = SaveIdeaRequest{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveIdeaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveIdeaRequest) ProtoMessage() {}

func (x *SaveIdeaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveIdeaRequest.ProtoReflect.Descriptor instead.
func (*SaveIdeaRequest) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{7}
}

func (x *SaveIdeaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveIdeaRequest) GetIdeaId() string {
	if x != nil {
		return x.IdeaId
	}
	return ""
}

type SaveIdeaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveIdeaResponse) Reset() {
	*x = SaveIdeaResponse{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveIdeaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveIdeaResponse) ProtoMessage() {}

func (x *SaveIdeaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveIdeaResponse.ProtoReflect.Descriptor instead.
func (*SaveIdeaResponse) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{8}
}

func (x *SaveIdeaResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RefineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Refinement    string                 `protobuf:"bytes,2,opt,name=refinement,proto3" json:"refinement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefineRequest) Reset() {
	*x = RefineRequest{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefineRequest) ProtoMessage() {}

func (x *RefineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefineRequest.ProtoReflect.Descriptor instead.
func (*RefineRequest) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{9}
}

func (x *RefineRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RefineRequest) GetRefinement() string {
	if x != nil {
		return x.Refinement
	}
	return ""
}

type RefineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        GenerationStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=surprise.v1.GenerationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefineResponse) Reset() {
	*x = RefineResponse{}
	mi := &file_surprise_v1_surprise_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefineResponse) ProtoMessage() {}

func (x *RefineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_surprise_v1_surprise_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefineResponse.ProtoReflect.Descriptor instead.
func (*RefineResponse) Descriptor() ([]byte, []int) {
	return file_surprise_v1_surprise_proto_rawDescGZIP(), []int{10}
}

func (x *RefineResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RefineResponse) GetStatus() GenerationStatus {
	if x != nil {
		return x.Status
	}
	return GenerationStatus_GENERATION_STATUS_UNSPECIFIED
}

var File_surprise_v1_surprise_proto protoreflect.FileDescriptor

const file_surprise_v1_surprise_proto_rawDesc = "" +
	"\n" +
	"\x1asurprise/v1/surprise.proto\x12\vsurprise.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xb0\x02\n" +
	"\x18RequestGenerationRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06userId\x12&\n" +
	"\n" +
	"holiday_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tholidayId\x12(\n" +
	"\vbudget_band\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"budgetBand\x12)\n" +
	"\x10preferences_text\x18\x04 \x01(\tR\x0fpreferencesText\x12\x17\n" +
	"\apoll_id\x18\x05 \x01(\tR\x06pollId\x12*\n" +
	"\x04tier\x18\x06 \x01(\x0e2\x16.surprise.v1.ModelTierR\x04tier\x120\n" +
	"\x0fidempotency_key\x18\a \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x0eidempotencyKey\"q\n" +
	"\x19RequestGenerationResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.surprise.v1.GenerationStatusR\x06status\"D\n" +
	"\x1aGetGenerationStatusRequest\x12&\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\trequestId\"p\n" +
	"\x1bGetGenerationStatusResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.surprise.v1.GenerationStatusR\x06status\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\rR\bprogress\"9\n" +
	"\x0fGetIdeasRequest\x12&\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\trequestId\"\x81\x02\n" +
	"\x04Idea\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1e\n" +
	"\vwhy_it_fits\x18\x04 \x01(\tR\twhyItFits\x12\x1d\n" +
	"\n" +
	"rough_cost\x18\x05 \x01(\tR\troughCost\x12\x15\n" +
	"\x06how_to\x18\x06 \x01(\tR\x05howTo\x12\x12\n" +
	"\x04rank\x18\a \x01(\rR\x04rank\x12J\n" +
	"\x11moderation_status\x18\b \x01(\x0e2\x1d.surprise.v1.ModerationStatusR\x10moderationStatus\";\n" +
	"\x10GetIdeasResponse\x12'\n" +
	"\x05ideas\x18\x01 \x03(\v2\x11.surprise.v1.IdeaR\x05ideas\"U\n" +
	"\x0fSaveIdeaRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06userId\x12 \n" +
	"\aidea_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06ideaId\"\"\n" +
	"\x10SaveIdeaResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"`\n" +
	"\rRefineRequest\x12&\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\trequestId\x12'\n" +
	"\n" +
	"refinement\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"refinement\"f\n" +
	"\x0eRefineResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.surprise.v1.GenerationStatusR\x06status*\xad\x01\n" +
	"\x10GenerationStatus\x12!\n" +
	"\x1dGENERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18GENERATION_STATUS_QUEUED\x10\x01\x12\x1d\n" +
	"\x19GENERATION_STATUS_RUNNING\x10\x02\x12\x1b\n" +
	"\x17GENERATION_STATUS_READY\x10\x03\x12\x1c\n" +
	"\x18GENERATION_STATUS_FAILED\x10\x04*S\n" +
	"\tModelTier\x12\x1a\n" +
	"\x16MODEL_TIER_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MODEL_TIER_SONNET\x10\x01\x12\x13\n" +
	"\x0fMODEL_TIER_OPUS\x10\x02*u\n" +
	"\x10ModerationStatus\x12!\n" +
	"\x1dMODERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aMODERATION_STATUS_APPROVED\x10\x01\x12\x1e\n" +
	"\x1aMODERATION_STATUS_REJECTED\x10\x022\xf5\x04\n" +
	"\x0fSurpriseService\x12~\n" +
	"\x11RequestGeneration\x12%.surprise.v1.RequestGenerationRequest\x1a&.surprise.v1.RequestGenerationResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/generations\x12\x95\x01\n" +
	"\x13GetGenerationStatus\x12'.surprise.v1.GetGenerationStatusRequest\x1a(.surprise.v1.GetGenerationStatusResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v1/generations/{request_id}/status\x12s\n" +
	"\bGetIdeas\x12\x1c.surprise.v1.GetIdeasRequest\x1a\x1d.surprise.v1.GetIdeasResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/generations/{request_id}/ideas\x12b\n" +
	"\bSaveIdea\x12\x1c.surprise.v1.SaveIdeaRequest\x1a\x1d.surprise.v1.SaveIdeaResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/ideas/save\x12q\n" +
	"\x06Refine\x12\x1a.surprise.v1.RefineRequest\x1a\x1b.surprise.v1.RefineResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/generations/{request_id}/refineB_Z]github.com/ilikyantigran/PerfectGift/services/backend/surprise/pkg/api/surprise/v1;surprisev1b\x06proto3"

var (
	file_surprise_v1_surprise_proto_rawDescOnce sync.Once
	file_surprise_v1_surprise_proto_rawDescData []byte
)

func file_surprise_v1_surprise_proto_rawDescGZIP() []byte {
	file_surprise_v1_surprise_proto_rawDescOnce.Do(func() {
		file_surprise_v1_surprise_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_surprise_v1_surprise_proto_rawDesc), len(file_surprise_v1_surprise_proto_rawDesc)))
	})
	return file_surprise_v1_surprise_proto_rawDescData
}

var file_surprise_v1_surprise_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_surprise_v1_surprise_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_surprise_v1_surprise_proto_goTypes = []any{
	(GenerationStatus)(0),               // 0: surprise.v1.GenerationStatus
	(ModelTier)(0),                      // 1: surprise.v1.ModelTier
	(ModerationStatus)(0),               // 2: surprise.v1.ModerationStatus
	(*RequestGenerationRequest)(nil),    // 3: surprise.v1.RequestGenerationRequest
	(*RequestGenerationResponse)(nil),   // 4: surprise.v1.RequestGenerationResponse
	(*GetGenerationStatusRequest)(nil),  // 5: surprise.v1.GetGenerationStatusRequest
	(*GetGenerationStatusResponse)(nil), // 6: surprise.v1.GetGenerationStatusResponse
	(*GetIdeasRequest)(nil),             // 7: surprise.v1.GetIdeasRequest
	(*Idea)(nil),                        // 8: surprise.v1.Idea
	(*GetIdeasResponse)(nil),            // 9: surprise.v1.GetIdeasResponse
	(*SaveIdeaRequest)(nil),             // 10: surprise.v1.SaveIdeaRequest
	(*SaveIdeaResponse)(nil),            // 11: surprise.v1.SaveIdeaResponse
	(*RefineRequest)(nil),               // 12: surprise.v1.RefineRequest
	(*RefineResponse)(nil),              // 13: surprise.v1.RefineResponse
}
var file_surprise_v1_surprise_proto_depIdxs = []int32{
	1,  // 0: surprise.v1.RequestGenerationRequest.tier:type_name -> surprise.v1.ModelTier
	0,  // 1: surprise.v1.RequestGenerationResponse.status:type_name -> surprise.v1.GenerationStatus
	0,  // 2: surprise.v1.GetGenerationStatusResponse.status:type_name -> surprise.v1.GenerationStatus
	2,  // 3: surprise.v1.Idea.moderation_status:type_name -> surprise.v1.ModerationStatus
	8,  // 4: surprise.v1.GetIdeasResponse.ideas:type_name -> surprise.v1.Idea
	0,  // 5: surprise.v1.RefineResponse.status:type_name -> surprise.v1.GenerationStatus
	3,  // 6: surprise.v1.SurpriseService.RequestGeneration:input_type -> surprise.v1.RequestGenerationRequest
	5,  // 7: surprise.v1.SurpriseService.GetGenerationStatus:input_type -> surprise.v1.GetGenerationStatusRequest
	7,  // 8: surprise.v1.SurpriseService.GetIdeas:input_type -> surprise.v1.GetIdeasRequest
	10, // 9: surprise.v1.SurpriseService.SaveIdea:input_type -> surprise.v1.SaveIdeaRequest
	12, // 10: surprise.v1.SurpriseService.Refine:input_type -> surprise.v1.RefineRequest
	4,  // 11: surprise.v1.SurpriseService.RequestGeneration:output_type -> surprise.v1.RequestGenerationResponse
	6,  // 12: surprise.v1.SurpriseService.GetGenerationStatus:output_type -> surprise.v1.GetGenerationStatusResponse
	9,  // 13: surprise.v1.SurpriseService.GetIdeas:output_type -> surprise.v1.GetIdeasResponse
	11, // 14: surprise.v1.SurpriseService.SaveIdea:output_type -> surprise.v1.SaveIdeaResponse
	13, // 15: surprise.v1.SurpriseService.Refine:output_type -> surprise.v1.RefineResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_surprise_v1_surprise_proto_init() }
func file_surprise_v1_surprise_proto_init() {
	if File_surprise_v1_surprise_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_surprise_v1_surprise_proto_rawDesc), len(file_surprise_v1_surprise_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_surprise_v1_surprise_proto_goTypes,
		DependencyIndexes: file_surprise_v1_surprise_proto_depIdxs,
		EnumInfos:         file_surprise_v1_surprise_proto_enumTypes,
		MessageInfos:      file_surprise_v1_surprise_proto_msgTypes,
	}.Build()
	File_surprise_v1_surprise_proto = out.File
	file_surprise_v1_surprise_proto_goTypes = nil
	file_surprise_v1_surprise_proto_depIdxs = nil
}
